#!/usr/bin/env python3
"""
Write the ICC profiles the colour corpus needs.

Why these exist
---------------
Until this ran, no fixture in this repository carried a real ICC profile.
The three that claimed to were placeholders - `tests/data/png/generate.py`
used the eleven bytes `b"minimal_icc"` - written to assert that an opaque
blob survives a round trip, which they do correctly.  What they could not do
is tell a correct colour transform from one that does nothing, because
neither produces any change on a corpus that carries no colour.

So these are real: a CMM parses them, reports the primaries and curves below,
and transforms pixels with them.  `tests/data/icc/verify_icc.py` checks that
against littleCMS, through the pinned Pillow image, and is what stops this
file's arithmetic being graded by itself.

The unmistakable one
--------------------
`swap_rg.icc` names sRGB's green colorant as its red and sRGB's red as its
green.  Convert an image tagged with it into sRGB and the two channels
exchange - visibly, on every pixel that is not grey.  It is here because a
corpus of *plausible* profiles cannot catch an engine that quietly does
nothing: every profile below is close enough to sRGB that a missing
transform looks like a rounding difference.  This one does not.

Colorants are computed rather than transcribed
----------------------------------------------
`src/color/icc_synth.c` tabulates published D50-adapted colorants, and says
why: a consumer comparing its profile with everyone else's should find the
same numbers, not a rounding of them.  This file does the opposite on
purpose.  It derives the colorants from the primaries with a Bradford
adaptation, so the corpus is not generated by the same method the library
uses - a fixture built the subject's own way grades the subject's
arithmetic against itself.  The two are cross-checked in the verifier.

Determinism
-----------
The date field is zeroed and no profile ID is written, so regenerating
produces identical bytes.  A generator that stamped the clock would make
every run a diff.
"""
import os
import struct
import sys

OUT = os.path.dirname(os.path.abspath(__file__))

# The ICC PCS illuminant: D50, as ICC.1 fixes it.
D50_XYZ = (0.9642, 1.0000, 0.8249)

# CIE 1931 chromaticities.  Same numbers as src/color/color.c's table, which
# is the point of contact between the two - the verifier checks that a
# profile built from these is identified by the library as the same space.
GAMUTS = {
    "srgb":      {"white": (0.3127, 0.3290), "r": (0.6400, 0.3300),
                  "g": (0.3000, 0.6000),     "b": (0.1500, 0.0600)},
    "adobergb":  {"white": (0.3127, 0.3290), "r": (0.6400, 0.3300),
                  "g": (0.2100, 0.7100),     "b": (0.1500, 0.0600)},
    "displayp3": {"white": (0.3127, 0.3290), "r": (0.6800, 0.3200),
                  "g": (0.2650, 0.6900),     "b": (0.1500, 0.0600)},
}

BRADFORD = ((0.8951, 0.2664, -0.1614),
            (-0.7502, 1.7135, 0.0367),
            (0.0389, -0.0685, 1.0296))


def mat_mul(a, b):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(3))
                       for j in range(3)) for i in range(3))


def mat_vec(m, v):
    return tuple(sum(m[i][k] * v[k] for k in range(3)) for i in range(3))


def mat_inv(m):
    (a, b, c), (d, e, f), (g, h, i) = m
    det = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    if abs(det) < 1e-12:
        raise ValueError("singular")
    return (
        ((e * i - f * h) / det, -(b * i - c * h) / det, (b * f - c * e) / det),
        (-(d * i - f * g) / det, (a * i - c * g) / det, -(a * f - c * d) / det),
        ((d * h - e * g) / det, -(a * h - b * g) / det, (a * e - b * d) / det))


def xy_to_XYZ(xy, Y=1.0):
    x, y = xy
    return (x * Y / y, Y, (1.0 - x - y) * Y / y)


def colorants(gamut):
    """The three D50-adapted colorants an ICC matrix profile states.

    Two steps, both standard: build the RGB-to-XYZ matrix for the primaries
    under their own white, then Bradford-adapt it from that white to D50,
    which is the illuminant the PCS is fixed at.
    """
    r, g, b = (xy_to_XYZ(gamut[k]) for k in ("r", "g", "b"))
    m = tuple(zip(r, g, b))                    # columns are the primaries
    w = xy_to_XYZ(gamut["white"])
    scale = mat_vec(mat_inv(m), w)
    rgb_to_xyz = tuple(tuple(m[i][j] * scale[j] for j in range(3))
                       for i in range(3))

    cone_src = mat_vec(BRADFORD, w)
    cone_dst = mat_vec(BRADFORD, D50_XYZ)
    ratio = tuple((cone_dst[i] / cone_src[i]) for i in range(3))
    diag = tuple(tuple(ratio[i] if i == j else 0.0 for j in range(3))
                 for i in range(3))
    adapt = mat_mul(mat_inv(BRADFORD), mat_mul(diag, BRADFORD))
    adapted = mat_mul(adapt, rgb_to_xyz)
    # Columns back to (R, G, B) colorant triples.
    return tuple(tuple(adapted[i][j] for i in range(3)) for j in range(3))


def s15f16(v):
    return struct.pack(">i", int(round(v * 65536.0)))


def pad4(n):
    return (4 - (n % 4)) % 4


def tag_xyz(triple):
    return b"XYZ " + b"\0" * 4 + b"".join(s15f16(v) for v in triple)


def tag_curv_gamma(gamma):
    """curveType with one entry: a u8Fixed8 gamma."""
    return b"curv" + b"\0" * 4 + struct.pack(">I", 1) + \
        struct.pack(">H", int(round(gamma * 256.0)))


def tag_curv_samples(samples):
    """curveType with N uint16 samples - the sampled-curve path."""
    return b"curv" + b"\0" * 4 + struct.pack(">I", len(samples)) + \
        b"".join(struct.pack(">H", s) for s in samples)


def srgb_curve_samples(n=1024):
    """The sRGB decoding curve, sampled - IEC 61966-2.1."""
    out = []
    for i in range(n):
        c = i / (n - 1)
        lin = c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
        out.append(min(65535, max(0, int(round(lin * 65535.0)))))
    return out


def tag_desc(text):
    """textDescriptionType (v2): ASCII, then empty Unicode and ScriptCode."""
    ascii_bytes = text.encode("ascii") + b"\0"
    return (b"desc" + b"\0" * 4 + struct.pack(">I", len(ascii_bytes)) +
            ascii_bytes +
            struct.pack(">I", 0) +      # Unicode language code
            struct.pack(">I", 0) +      # Unicode count
            struct.pack(">H", 0) +      # ScriptCode code
            struct.pack(">B", 0) +      # ScriptCode count
            b"\0" * 67)                 # ScriptCode description


def tag_text(text):
    return b"text" + b"\0" * 4 + text.encode("ascii") + b"\0"


def build_profile(space, tags, desc, version=0x02100000):
    """Assemble a v2 profile from an ordered list of (signature, payload)."""
    tags = [(sig, payload) for sig, payload in tags]
    count = len(tags)
    table_size = 4 + count * 12
    offset = 128 + table_size
    entries = []
    body = bytearray()
    for sig, payload in tags:
        entries.append((sig, 128 + table_size + len(body), len(payload)))
        body += payload
        body += b"\0" * pad4(len(body))
    total = 128 + table_size + len(body)

    h = bytearray(128)
    h[0:4] = struct.pack(">I", total)
    h[4:8] = b"\0" * 4                       # preferred CMM: none
    h[8:12] = struct.pack(">I", version)
    h[12:16] = b"mntr"
    h[16:20] = space
    h[20:24] = b"XYZ "
    h[24:36] = b"\0" * 12                    # date: zeroed, see the docstring
    h[36:40] = b"acsp"
    h[40:44] = b"\0" * 4
    h[44:48] = struct.pack(">I", 0)          # flags
    h[48:52] = b"\0" * 4
    h[52:56] = b"\0" * 4
    h[56:64] = b"\0" * 8
    h[64:68] = struct.pack(">I", 0)          # perceptual
    h[68:80] = b"".join(s15f16(v) for v in D50_XYZ)
    h[80:84] = b"\0" * 4
    h[84:100] = b"\0" * 16                   # profile ID: not computed
    h[100:128] = b"\0" * 28

    out = bytes(h) + struct.pack(">I", count)
    for sig, off, size in entries:
        out += sig + struct.pack(">II", off, size)
    out += bytes(body)
    assert len(out) == total, (len(out), total)
    assert desc  # the caller must name it; a nameless profile is a bad fixture
    return out


def rgb_profile(name, gamut_key, trc, desc, swap_rg=False):
    r, g, b = colorants(GAMUTS[gamut_key])
    if swap_rg:
        r, g = g, r
    tags = [
        (b"desc", tag_desc(desc)),
        (b"cprt", tag_text("No copyright, use freely.")),
        (b"wtpt", tag_xyz(D50_XYZ)),
        (b"rXYZ", tag_xyz(r)),
        (b"gXYZ", tag_xyz(g)),
        (b"bXYZ", tag_xyz(b)),
        (b"rTRC", trc),
        (b"gTRC", trc),
        (b"bTRC", trc),
    ]
    return build_profile(b"RGB ", tags, desc)


def gray_profile(name, gamma, desc):
    tags = [
        (b"desc", tag_desc(desc)),
        (b"cprt", tag_text("No copyright, use freely.")),
        (b"wtpt", tag_xyz(D50_XYZ)),
        (b"kTRC", tag_curv_gamma(gamma)),
    ]
    return build_profile(b"GRAY", tags, desc)


def main():
    g22 = tag_curv_gamma(2.2)
    linear = tag_curv_gamma(1.0)
    profiles = {
        "srgb_g22.icc": rgb_profile(
            "srgb_g22", "srgb", g22, "Ghoti test sRGB primaries, gamma 2.2"),
        "adobergb_g22.icc": rgb_profile(
            "adobergb_g22", "adobergb", g22,
            "Ghoti test Adobe RGB primaries, gamma 2.2"),
        "displayp3_g22.icc": rgb_profile(
            "displayp3_g22", "displayp3", g22,
            "Ghoti test Display P3 primaries, gamma 2.2"),
        # The discriminating fixture; see the module docstring.
        "swap_rg.icc": rgb_profile(
            "swap_rg", "srgb", linear,
            "Ghoti test red and green exchanged", swap_rg=True),
        "srgb_sampled_trc.icc": rgb_profile(
            "srgb_sampled_trc", "srgb",
            tag_curv_samples(srgb_curve_samples()),
            "Ghoti test sRGB primaries, sampled curve"),
        "gray_g22.icc": gray_profile("gray_g22", 2.2,
                                     "Ghoti test grayscale, gamma 2.2"),
    }
    for name, data in sorted(profiles.items()):
        with open(os.path.join(OUT, name), "wb") as f:
            f.write(data)
        print("  %-24s %5d bytes" % (name, len(data)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
