/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Image.
 *
 * Ghoti.io Image is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Image is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file namespace.h
 *
 * Maps every public name of this library into its version namespace.
 *
 * Generated from the built library's dynamic symbol table and kept in one file
 * rather than beside each declaration: a type rename has to be in effect
 * before any struct tag that uses the name, and an internal header may define
 * such a tag without including the public header that declares the typedef.
 *
 * `make check-symbols` fails if an exported symbol is missing from this list.
 *
 * See CONVENTIONS.md section 4.
 */

#ifndef GHOTI_IO_GIMG_NAMESPACE_H
#define GHOTI_IO_GIMG_NAMESPACE_H

#include <ghoti.io/image/libver.h>

/// @cond HIDDEN_SYMBOLS
#define GIMG_Blend_Op GHOTIIO_IMAGE(GIMG_Blend_Op)
#define GIMG_Channel_Model GHOTIIO_IMAGE(GIMG_Channel_Model)
#define GIMG_Channel_Type GHOTIIO_IMAGE(GIMG_Channel_Type)
#define GIMG_Codec GHOTIIO_IMAGE(GIMG_Codec)
#define GIMG_Decode_Options GHOTIIO_IMAGE(GIMG_Decode_Options)
#define GIMG_Diag_Severity GHOTIIO_IMAGE(GIMG_Diag_Severity)
#define GIMG_Diagnostic GHOTIIO_IMAGE(GIMG_Diagnostic)
#define GIMG_Diagnostics GHOTIIO_IMAGE(GIMG_Diagnostics)
#define GIMG_Dispose_Op GHOTIIO_IMAGE(GIMG_Dispose_Op)
#define GIMG_Doc GHOTIIO_IMAGE(GIMG_Doc)
#define GIMG_Item GHOTIIO_IMAGE(GIMG_Item)
#define GIMG_JPEG_Progressive_Config GHOTIIO_IMAGE(GIMG_JPEG_Progressive_Config)
#define GIMG_JPEG_Progressive_Scan GHOTIIO_IMAGE(GIMG_JPEG_Progressive_Scan)
#define GIMG_Limits GHOTIIO_IMAGE(GIMG_Limits)
#define GIMG_JPEG_Tables GHOTIIO_IMAGE(GIMG_JPEG_Tables)
#define gimg_jpeg_tables_load GHOTIIO_IMAGE(gimg_jpeg_tables_load)
#define gimg_jpeg_tables_destroy GHOTIIO_IMAGE(gimg_jpeg_tables_destroy)
#define GIMG_Load_Options GHOTIIO_IMAGE(GIMG_Load_Options)
#define GIMG_Meta_Common GHOTIIO_IMAGE(GIMG_Meta_Common)
#define GIMG_Meta_Policy GHOTIIO_IMAGE(GIMG_Meta_Policy)
#define GIMG_Meta_Raw GHOTIIO_IMAGE(GIMG_Meta_Raw)
#define GIMG_Orientation GHOTIIO_IMAGE(GIMG_Orientation)
#define gimg_pixel_format_channel_bits GHOTIIO_IMAGE(gimg_pixel_format_channel_bits)
#define gimg_pixel_format_multichannel GHOTIIO_IMAGE(gimg_pixel_format_multichannel)
#define GIMG_PIXEL_CMYK8 GHOTIIO_IMAGE(GIMG_PIXEL_CMYK8)
#define GIMG_PIXEL_CMYK12 GHOTIIO_IMAGE(GIMG_PIXEL_CMYK12)
#define GIMG_PIXEL_CMYK16 GHOTIIO_IMAGE(GIMG_PIXEL_CMYK16)
#define GIMG_PIXEL_GRAY12 GHOTIIO_IMAGE(GIMG_PIXEL_GRAY12)
#define GIMG_PIXEL_GRAY16 GHOTIIO_IMAGE(GIMG_PIXEL_GRAY16)
#define GIMG_PIXEL_GRAY8 GHOTIIO_IMAGE(GIMG_PIXEL_GRAY8)
#define GIMG_PIXEL_RGBA12 GHOTIIO_IMAGE(GIMG_PIXEL_RGBA12)
#define GIMG_PIXEL_RGBA16 GHOTIIO_IMAGE(GIMG_PIXEL_RGBA16)
#define GIMG_PIXEL_RGBA8 GHOTIIO_IMAGE(GIMG_PIXEL_RGBA8)
#define GIMG_Pixel_Format GHOTIIO_IMAGE(GIMG_Pixel_Format)
#define GIMG_Pixel_Layout GHOTIIO_IMAGE(GIMG_Pixel_Layout)
#define GIMG_Probe_Result GHOTIIO_IMAGE(GIMG_Probe_Result)
#define GIMG_Raster GHOTIIO_IMAGE(GIMG_Raster)
#define GIMG_Raster_Ownership GHOTIIO_IMAGE(GIMG_Raster_Ownership)
#define GIMG_Result GHOTIIO_IMAGE(GIMG_Result)
#define GIMG_Save_Options GHOTIIO_IMAGE(GIMG_Save_Options)
#define GIMG_Save_Report GHOTIIO_IMAGE(GIMG_Save_Report)
#define GIMG_Stream GHOTIIO_IMAGE(GIMG_Stream)
#define GIMG_Strictness GHOTIIO_IMAGE(GIMG_Strictness)
#define gimg_allocator_default GHOTIIO_IMAGE(gimg_allocator_default)
#define gimg_alpha_premultiply GHOTIIO_IMAGE(gimg_alpha_premultiply)
#define gimg_alpha_unpremultiply GHOTIIO_IMAGE(gimg_alpha_unpremultiply)
#define gimg_bitdepth_12_to_16 GHOTIIO_IMAGE(gimg_bitdepth_12_to_16)
#define gimg_bitdepth_12_to_8 GHOTIIO_IMAGE(gimg_bitdepth_12_to_8)
#define gimg_bitdepth_16_to_12 GHOTIIO_IMAGE(gimg_bitdepth_16_to_12)
#define gimg_bitdepth_16_to_8 GHOTIIO_IMAGE(gimg_bitdepth_16_to_8)
#define gimg_bitdepth_8_to_12 GHOTIIO_IMAGE(gimg_bitdepth_8_to_12)
#define gimg_bitdepth_8_to_16 GHOTIIO_IMAGE(gimg_bitdepth_8_to_16)
#define gimg_codec_by_index GHOTIIO_IMAGE(gimg_codec_by_index)
#define gimg_codec_by_name GHOTIIO_IMAGE(gimg_codec_by_name)
#define gimg_codec_capabilities GHOTIIO_IMAGE(gimg_codec_capabilities)
#define gimg_codec_count GHOTIIO_IMAGE(gimg_codec_count)
#define gimg_codec_create_stub GHOTIIO_IMAGE(gimg_codec_create_stub)
#define gimg_codec_create_stub_with_allocator GHOTIIO_IMAGE(gimg_codec_create_stub_with_allocator)
#define gimg_codec_name GHOTIIO_IMAGE(gimg_codec_name)
#define gimg_codec_register GHOTIIO_IMAGE(gimg_codec_register)
#define gimg_diagnostics_append GHOTIIO_IMAGE(gimg_diagnostics_append)
#define gimg_diagnostics_clear GHOTIIO_IMAGE(gimg_diagnostics_clear)
#define gimg_diagnostics_destroy GHOTIIO_IMAGE(gimg_diagnostics_destroy)
#define gimg_diagnostics_init GHOTIIO_IMAGE(gimg_diagnostics_init)
#define gimg_doc_copy GHOTIIO_IMAGE(gimg_doc_copy)
#define gimg_doc_copy_with_allocator GHOTIIO_IMAGE(gimg_doc_copy_with_allocator)
#define gimg_doc_create GHOTIIO_IMAGE(gimg_doc_create)
#define gimg_doc_create_with_allocator GHOTIIO_IMAGE(gimg_doc_create_with_allocator)
#define gimg_doc_destroy GHOTIIO_IMAGE(gimg_doc_destroy)
#define gimg_doc_ensure_meta_common GHOTIIO_IMAGE(gimg_doc_ensure_meta_common)
#define gimg_doc_ensure_meta_raw GHOTIIO_IMAGE(gimg_doc_ensure_meta_raw)
#define gimg_doc_from_raster GHOTIIO_IMAGE(gimg_doc_from_raster)
#define gimg_doc_from_raster_with_allocator GHOTIIO_IMAGE(gimg_doc_from_raster_with_allocator)
#define gimg_doc_item GHOTIIO_IMAGE(gimg_doc_item)
#define gimg_doc_item_count GHOTIIO_IMAGE(gimg_doc_item_count)
#define gimg_doc_clear_loop_count GHOTIIO_IMAGE(gimg_doc_clear_loop_count)
#define gimg_doc_clear_pixel_aspect_ratio GHOTIIO_IMAGE(gimg_doc_clear_pixel_aspect_ratio)
#define gimg_doc_set_pixel_aspect_ratio GHOTIIO_IMAGE(gimg_doc_set_pixel_aspect_ratio)
#define gimg_doc_pixel_aspect_ratio GHOTIIO_IMAGE(gimg_doc_pixel_aspect_ratio)
#define gimg_doc_clear_background_color GHOTIIO_IMAGE(gimg_doc_clear_background_color)
#define gimg_doc_set_background_color GHOTIIO_IMAGE(gimg_doc_set_background_color)
#define gimg_doc_background_color GHOTIIO_IMAGE(gimg_doc_background_color)
#define gimg_doc_load GHOTIIO_IMAGE(gimg_doc_load)
#define gimg_doc_loop_count GHOTIIO_IMAGE(gimg_doc_loop_count)
#define gimg_doc_meta_common GHOTIIO_IMAGE(gimg_doc_meta_common)
#define gimg_doc_meta_raw GHOTIIO_IMAGE(gimg_doc_meta_raw)
#define gimg_doc_save GHOTIIO_IMAGE(gimg_doc_save)
#define gimg_doc_set_item_count GHOTIIO_IMAGE(gimg_doc_set_item_count)
#define gimg_doc_set_loop_count GHOTIIO_IMAGE(gimg_doc_set_loop_count)
#define gimg_item_blend_op GHOTIIO_IMAGE(gimg_item_blend_op)
#define gimg_item_copy GHOTIIO_IMAGE(gimg_item_copy)
#define GIMG_Item_Role GHOTIIO_IMAGE(GIMG_Item_Role)
#define gimg_item_decode GHOTIIO_IMAGE(gimg_item_decode)
#define gimg_item_role GHOTIIO_IMAGE(gimg_item_role)
#define gimg_item_role_subject GHOTIIO_IMAGE(gimg_item_role_subject)
#define gimg_item_set_role GHOTIIO_IMAGE(gimg_item_set_role)
#define gimg_item_dispose_op GHOTIIO_IMAGE(gimg_item_dispose_op)
#define gimg_item_ensure_decoded GHOTIIO_IMAGE(gimg_item_ensure_decoded)
#define gimg_item_frame_delay GHOTIIO_IMAGE(gimg_item_frame_delay)
#define gimg_item_raster GHOTIIO_IMAGE(gimg_item_raster)
#define gimg_item_set_blend_op GHOTIIO_IMAGE(gimg_item_set_blend_op)
#define gimg_item_set_dispose_op GHOTIIO_IMAGE(gimg_item_set_dispose_op)
#define gimg_item_set_frame_delay GHOTIIO_IMAGE(gimg_item_set_frame_delay)
#define gimg_item_set_raster GHOTIIO_IMAGE(gimg_item_set_raster)
#define gimg_jpeg_default_ac_lum_dht_payload GHOTIIO_IMAGE(gimg_jpeg_default_ac_lum_dht_payload)
#define gimg_jpeg_default_ac_refine_dht_payload GHOTIIO_IMAGE(gimg_jpeg_default_ac_refine_dht_payload)
#define gimg_jpeg_ext_ac_chr_bits GHOTIIO_IMAGE(gimg_jpeg_ext_ac_chr_bits)
#define gimg_jpeg_ext_ac_chr_vals GHOTIIO_IMAGE(gimg_jpeg_ext_ac_chr_vals)
#define gimg_jpeg_ext_ac_lum_bits GHOTIIO_IMAGE(gimg_jpeg_ext_ac_lum_bits)
#define gimg_jpeg_ext_ac_lum_vals GHOTIIO_IMAGE(gimg_jpeg_ext_ac_lum_vals)
#define gimg_jpeg_ext_dc_chr_bits GHOTIIO_IMAGE(gimg_jpeg_ext_dc_chr_bits)
#define gimg_jpeg_ext_dc_chr_vals GHOTIIO_IMAGE(gimg_jpeg_ext_dc_chr_vals)
#define gimg_jpeg_ext_dc_lum_bits GHOTIIO_IMAGE(gimg_jpeg_ext_dc_lum_bits)
#define gimg_jpeg_ext_dc_lum_vals GHOTIIO_IMAGE(gimg_jpeg_ext_dc_lum_vals)
#define gimg_jpeg_inv_zigzag GHOTIIO_IMAGE(gimg_jpeg_inv_zigzag)
#define gimg_jpeg_std_ac_chr_bits GHOTIIO_IMAGE(gimg_jpeg_std_ac_chr_bits)
#define gimg_jpeg_std_ac_chr_vals GHOTIIO_IMAGE(gimg_jpeg_std_ac_chr_vals)
#define gimg_jpeg_std_ac_lum_bits GHOTIIO_IMAGE(gimg_jpeg_std_ac_lum_bits)
#define gimg_jpeg_std_ac_lum_vals GHOTIIO_IMAGE(gimg_jpeg_std_ac_lum_vals)
#define gimg_jpeg_std_ac_refine_bits GHOTIIO_IMAGE(gimg_jpeg_std_ac_refine_bits)
#define gimg_jpeg_std_ac_refine_vals GHOTIIO_IMAGE(gimg_jpeg_std_ac_refine_vals)
#define gimg_jpeg_std_chrominance_quant GHOTIIO_IMAGE(gimg_jpeg_std_chrominance_quant)
#define gimg_jpeg_std_dc_chr_bits GHOTIIO_IMAGE(gimg_jpeg_std_dc_chr_bits)
#define gimg_jpeg_std_dc_chr_vals GHOTIIO_IMAGE(gimg_jpeg_std_dc_chr_vals)
#define gimg_jpeg_std_dc_lum_bits GHOTIIO_IMAGE(gimg_jpeg_std_dc_lum_bits)
#define gimg_jpeg_std_dc_lum_vals GHOTIIO_IMAGE(gimg_jpeg_std_dc_lum_vals)
#define gimg_jpeg_std_luminance_quant GHOTIIO_IMAGE(gimg_jpeg_std_luminance_quant)
#define gimg_jpeg_zigzag GHOTIIO_IMAGE(gimg_jpeg_zigzag)
#define gimg_limits_default GHOTIIO_IMAGE(gimg_limits_default)
#define gimg_meta_common_create GHOTIIO_IMAGE(gimg_meta_common_create)
#define gimg_meta_common_create_with_allocator GHOTIIO_IMAGE(gimg_meta_common_create_with_allocator)
#define gimg_meta_common_description GHOTIIO_IMAGE(gimg_meta_common_description)
#define gimg_meta_common_destroy GHOTIIO_IMAGE(gimg_meta_common_destroy)
#define gimg_meta_common_dpi GHOTIIO_IMAGE(gimg_meta_common_dpi)
#define gimg_meta_common_orientation GHOTIIO_IMAGE(gimg_meta_common_orientation)
#define gimg_meta_common_set_description GHOTIIO_IMAGE(gimg_meta_common_set_description)
#define gimg_meta_common_set_dpi GHOTIIO_IMAGE(gimg_meta_common_set_dpi)
#define gimg_meta_common_set_orientation GHOTIIO_IMAGE(gimg_meta_common_set_orientation)
#define gimg_meta_raw_attach GHOTIIO_IMAGE(gimg_meta_raw_attach)
#define gimg_meta_raw_copy GHOTIIO_IMAGE(gimg_meta_raw_copy)
#define gimg_meta_raw_copy_with_allocator GHOTIIO_IMAGE(gimg_meta_raw_copy_with_allocator)
#define gimg_meta_raw_create GHOTIIO_IMAGE(gimg_meta_raw_create)
#define gimg_meta_raw_create_with_allocator GHOTIIO_IMAGE(gimg_meta_raw_create_with_allocator)
#define gimg_meta_raw_destroy GHOTIIO_IMAGE(gimg_meta_raw_destroy)
#define gimg_meta_raw_get GHOTIIO_IMAGE(gimg_meta_raw_get)
#define gimg_ops_apply_orientation GHOTIIO_IMAGE(gimg_ops_apply_orientation)
#define gimg_ops_convert_bit_depth GHOTIIO_IMAGE(gimg_ops_convert_bit_depth)
#define gimg_ops_count_colors GHOTIIO_IMAGE(gimg_ops_count_colors)
#define gimg_ops_palette_apply GHOTIIO_IMAGE(gimg_ops_palette_apply)
#define gimg_ops_palette_build GHOTIIO_IMAGE(gimg_ops_palette_build)
#define gimg_ops_palette_from_raster GHOTIIO_IMAGE(gimg_ops_palette_from_raster)
#define gimg_ops_quantize GHOTIIO_IMAGE(gimg_ops_quantize)
#define gimg_ops_crop GHOTIIO_IMAGE(gimg_ops_crop)
#define gimg_ops_flip_horizontal GHOTIIO_IMAGE(gimg_ops_flip_horizontal)
#define gimg_ops_flip_vertical GHOTIIO_IMAGE(gimg_ops_flip_vertical)
#define gimg_ops_rotate_90_cw GHOTIIO_IMAGE(gimg_ops_rotate_90_cw)
#define gimg_ops_rotate_90_ccw GHOTIIO_IMAGE(gimg_ops_rotate_90_ccw)
#define gimg_ops_rotate_180 GHOTIIO_IMAGE(gimg_ops_rotate_180)
#define gimg_ops_composite GHOTIIO_IMAGE(gimg_ops_composite)
#define gimg_ops_resize GHOTIIO_IMAGE(gimg_ops_resize)
#define gimg_resize_options_default GHOTIIO_IMAGE(gimg_resize_options_default)
#define gimg_ops_convert_pixel_format GHOTIIO_IMAGE(gimg_ops_convert_pixel_format)
#define gimg_ops_raster_equal GHOTIIO_IMAGE(gimg_ops_raster_equal)
#define gimg_probe GHOTIIO_IMAGE(gimg_probe)
#define gimg_raster_allocator GHOTIIO_IMAGE(gimg_raster_allocator)
#define gimg_raster_bytes_per_pixel GHOTIIO_IMAGE(gimg_raster_bytes_per_pixel)
#define gimg_raster_color_info_const GHOTIIO_IMAGE(gimg_raster_color_info_const)
#define gimg_raster_copy GHOTIIO_IMAGE(gimg_raster_copy)
#define gimg_raster_copy_with_allocator GHOTIIO_IMAGE(gimg_raster_copy_with_allocator)
#define gimg_raster_create GHOTIIO_IMAGE(gimg_raster_create)
#define gimg_raster_create_with_allocator GHOTIIO_IMAGE(gimg_raster_create_with_allocator)
#define gimg_raster_destroy GHOTIIO_IMAGE(gimg_raster_destroy)
#define gimg_raster_format GHOTIIO_IMAGE(gimg_raster_format)
#define gimg_raster_height GHOTIIO_IMAGE(gimg_raster_height)
#define gimg_raster_ownership GHOTIIO_IMAGE(gimg_raster_ownership)
#define gimg_raster_pixels GHOTIIO_IMAGE(gimg_raster_pixels)
#define gimg_raster_pixels_const GHOTIIO_IMAGE(gimg_raster_pixels_const)
#define gimg_raster_set_color_info GHOTIIO_IMAGE(gimg_raster_set_color_info)
#define gimg_raster_stride_bytes GHOTIIO_IMAGE(gimg_raster_stride_bytes)
#define gimg_raster_width GHOTIIO_IMAGE(gimg_raster_width)
#define gimg_result_string GHOTIIO_IMAGE(gimg_result_string)
#define gimg_stream_create_memory GHOTIIO_IMAGE(gimg_stream_create_memory)
#define gimg_stream_create_memory_chunked GHOTIIO_IMAGE(gimg_stream_create_memory_chunked)
#define gimg_stream_create_memory_chunked_with_allocator GHOTIIO_IMAGE(gimg_stream_create_memory_chunked_with_allocator)
#define gimg_stream_create_memory_no_seek GHOTIIO_IMAGE(gimg_stream_create_memory_no_seek)
#define gimg_stream_create_memory_no_seek_chunked GHOTIIO_IMAGE(gimg_stream_create_memory_no_seek_chunked)
#define gimg_stream_create_memory_no_seek_chunked_with_allocator GHOTIIO_IMAGE(gimg_stream_create_memory_no_seek_chunked_with_allocator)
#define gimg_stream_create_memory_no_seek_with_allocator GHOTIIO_IMAGE(gimg_stream_create_memory_no_seek_with_allocator)
#define gimg_stream_create_memory_output GHOTIIO_IMAGE(gimg_stream_create_memory_output)
#define gimg_stream_create_memory_output_with_allocator GHOTIIO_IMAGE(gimg_stream_create_memory_output_with_allocator)
#define gimg_stream_create_memory_with_allocator GHOTIIO_IMAGE(gimg_stream_create_memory_with_allocator)
#define gimg_stream_destroy GHOTIIO_IMAGE(gimg_stream_destroy)
#define gimg_stream_error GHOTIIO_IMAGE(gimg_stream_error)
#define gimg_stream_output_buffer GHOTIIO_IMAGE(gimg_stream_output_buffer)
#define gimg_stream_peek GHOTIIO_IMAGE(gimg_stream_peek)
#define gimg_stream_read GHOTIIO_IMAGE(gimg_stream_read)
#define gimg_stream_read_exact GHOTIIO_IMAGE(gimg_stream_read_exact)
#define gimg_stream_seek GHOTIIO_IMAGE(gimg_stream_seek)
#define gimg_stream_size GHOTIIO_IMAGE(gimg_stream_size)
#define gimg_stream_skip GHOTIIO_IMAGE(gimg_stream_skip)
#define gimg_stream_tell GHOTIIO_IMAGE(gimg_stream_tell)
#define gimg_stream_write GHOTIIO_IMAGE(gimg_stream_write)
#define gimg_version_major GHOTIIO_IMAGE(gimg_version_major)
#define gimg_version_minor GHOTIIO_IMAGE(gimg_version_minor)
#define gimg_version_patch GHOTIIO_IMAGE(gimg_version_patch)
#define gimg_version_string GHOTIIO_IMAGE(gimg_version_string)
/// @endcond

#endif // GHOTI_IO_GIMG_NAMESPACE_H
