#!/usr/bin/env python3
"""Generate the VP8 coefficient tables from RFC 6386.

Reads the official text (third_party/rfc6386/rfc6386.txt, pinned by
tools/webp/rfc6386.sha256) and writes src/codec/webp/webp_vp8_proba.inc.
The output is committed, because a build must need neither the network nor
Python. This script is run when the pin changes, and by ``make
check-vp8-tables`` to prove that what is committed is what this script
produces from that text.

The numbers are taken from the RFC's own code blocks. Nothing here is copied
from another library. Page headers and form feeds are dropped before parsing,
because the RFC inserts them in the middle of the tables.

Usage:
    tools/webp/gen_vp8_tables.py [--rfc FILE] [--out DIR]

Copyright 2026 by Corey Pennycuff
"""

import argparse
import hashlib
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DEFAULT_RFC = os.path.join(ROOT, "third_party", "rfc6386", "rfc6386.txt")
DEFAULT_OUT = os.path.join(ROOT, "src", "codec", "webp")
PIN = os.path.join(ROOT, "tools", "webp", "rfc6386.sha256")

# RFC 6386 section 9.6: the dequantization index is 7 bits, so section 14.1's
# dc_qlookup has 128 entries. The RFC names the bound QINDEX_RANGE and does
# not give the integer in the table's own section.
DC_QLOOKUP_LEN = 128

LICENSE = """\
/*
 * SPDX-License-Identifier: LGPL-3.0-only
 *
 * Copyright (C) 2026 Corey Pennycuff
 *
 * This file is part of Ghoti.io Image.
 *
 * Ghoti.io Image is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Ghoti.io Image is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
"""

BANNER = """\
/**
 * @file
 *
 * GENERATED by tools/webp/gen_vp8_tables.py from RFC 6386. Do not edit.
 *
 * The numbers are the tables in that RFC's text. Regenerate with
 * tools/webp/gen_vp8_tables.py after tools/webp/fetch_rfc6386.sh.
 * Verify with make check-vp8-tables.
 *
 *   gimg_vp8_coeffs_update_proba   section 13.4  coeff_update_probs
 *   gimg_vp8_coeffs_proba0         section 13.5  default_coeff_probs
 *   gimg_vp8_bands                 section 13.3  coeff_bands
 *   gimg_vp8_pcat1 .. pcat6        section 13.2  Pcat1 .. Pcat6
 *   gimg_vp8_dc_qlookup            section 14.1  dc_qlookup
 *
 * Probabilities and the DC lookup are stored as uint8_t. Every value in
 * those tables is in 0..255. coeff_bands is the sixteen entries the RFC
 * declares, and no sentinel past them.
 */
"""


def die(msg):
    sys.exit("gen_vp8_tables.py: " + msg)


def pinned_digest():
    with open(PIN, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line and not line.startswith("#"):
                return line
    die("no digest in " + PIN)


def load_rfc(path):
    with open(path, "rb") as fh:
        raw = fh.read()
    digest = hashlib.sha256(raw).hexdigest()
    want = pinned_digest()
    if digest != want:
        die("RFC text digest %s does not match the pin %s" % (digest, want))
    text = raw.decode("utf-8")
    kept = []
    for line in text.replace("\f", "\n").splitlines():
        stripped = line.strip()
        if stripped.startswith("Bankoski, et al."):
            continue
        if stripped.startswith("RFC 6386") and "VP8 Data Format" in stripped:
            continue
        kept.append(line)
    return "\n".join(kept)


def parse_initializer(text, decl):
    """The brace initializer that follows the first occurrence of decl."""
    at = text.find(decl)
    if at < 0:
        die("RFC text has no %r" % decl)
    brace = text.find("{", at)
    if brace < 0:
        die("RFC text has no initializer after %r" % decl)
    value, end = parse_value(text, brace, decl)
    return value


def parse_value(text, i, decl):
    n = len(text)
    while i < n and text[i].isspace():
        i += 1
    if i >= n:
        die("initializer for %r ended early" % decl)
    if text[i] == "{":
        i += 1
        items = []
        while True:
            while i < n and (text[i].isspace() or text[i] == ","):
                i += 1
            if i >= n:
                die("unclosed initializer for %r" % decl)
            if text[i] == "}":
                return items, i + 1
            item, i = parse_value(text, i, decl)
            items.append(item)
    if text[i] == "-" or text[i].isdigit():
        j = i + 1 if text[i] == "-" else i
        while j < n and text[j].isdigit():
            j += 1
        if j == i or (text[i] == "-" and j == i + 1):
            die("bad number in %r" % decl)
        return int(text[i:j]), j
    die("unexpected %r in %r" % (text[i:i + 20], decl))


def expect_shape(value, shape, decl):
    """shape is a list of lengths from the outside in. The last length is
    the number of ints in each innermost row, or 0 when the value is a flat
    list of ints whose length is shape[0]."""
    if shape == [0]:
        return
    if not shape:
        if not isinstance(value, int):
            die("%s: expected an int" % decl)
        return
    if not isinstance(value, list) or len(value) != shape[0]:
        got = len(value) if isinstance(value, list) else type(value).__name__
        die("%s: expected %d entries, got %s" % (decl, shape[0], got))
    for item in value:
        expect_shape(item, shape[1:], decl)


def expect_bytes(value, decl):
    if isinstance(value, int):
        if value < 0 or value > 255:
            die("%s: value %d does not fit in a byte" % (decl, value))
        return
    for item in value:
        expect_bytes(item, decl)


def fmt_ints(nums, indent):
    """One or more lines of comma-separated ints, wrapped under 80 columns."""
    pad = " " * indent
    lines = []
    current = pad
    for i, n in enumerate(nums):
        piece = str(n)
        if i + 1 < len(nums):
            piece += ","
        if current == pad:
            current += piece
        elif len(current) + 1 + len(piece) > 78:
            lines.append(current)
            current = pad + piece
        else:
            current += " " + piece
    lines.append(current)
    return lines


def fmt_value(value, indent):
    pad = " " * indent
    if isinstance(value, int):
        return [str(value)]
    if value and all(isinstance(x, int) for x in value):
        inner = ", ".join(str(n) for n in value)
        return [pad + "{ " + inner + " }"]
    lines = [pad + "{"]
    for i, item in enumerate(value):
        rendered = fmt_value(item, indent + 2)
        if i + 1 < len(value):
            rendered[-1] += ","
        lines.extend(rendered)
    lines.append(pad + "}")
    return lines


def emit_array(name, dims, value, indent_body=2):
    dim = "".join("[%s]" % d for d in dims)
    decl = "static const uint8_t %s%s = {" % (name, dim)
    if len(decl) <= 80:
        lines = [decl]
    else:
        # The dimensions are part of the type. Split them so a generated
        # line stays inside the column limit the rest of the library uses.
        lines = ["static const uint8_t %s" % name]
        chunk = "    "
        for d in dims:
            piece = "[%s]" % d
            if len(chunk) + len(piece) > 78:
                lines.append(chunk)
                chunk = "    " + piece
            else:
                chunk += piece
        lines.append(chunk + " = {")
    if value and all(isinstance(x, int) for x in value):
        lines.extend(fmt_ints(value, indent_body))
        lines.append("};")
        return "\n".join(lines) + "\n"
    body = fmt_value(value, indent_body)
    # fmt_value wraps a list in its own braces; the declaration already has one.
    inner = body[1:-1]
    lines.extend(inner)
    lines.append("};")
    return "\n".join(lines) + "\n"


def generate(text):
    update = parse_initializer(
        text, "const Prob coeff_update_probs")
    default = parse_initializer(
        text, "const Prob default_coeff_probs")
    bands = parse_initializer(text, "const int coeff_bands [16]")
    pcats = [
        parse_initializer(text, "const Prob Pcat%d[]" % n) for n in range(1, 7)
    ]
    dc = parse_initializer(text, "static const int dc_qlookup[QINDEX_RANGE]")

    prob_shape = [4, 8, 3, 11]
    expect_shape(update, prob_shape, "coeff_update_probs")
    expect_shape(default, prob_shape, "default_coeff_probs")
    expect_bytes(update, "coeff_update_probs")
    expect_bytes(default, "default_coeff_probs")
    expect_shape(bands, [16], "coeff_bands")
    for n in bands:
        if not isinstance(n, int) or n < 0 or n > 7:
            die("coeff_bands: %r is not a band index" % (n,))
    pcat_lens = [2, 3, 4, 5, 6, 12]
    for n, (table, length) in enumerate(zip(pcats, pcat_lens), start=1):
        expect_shape(table, [length], "Pcat%d" % n)
        expect_bytes(table, "Pcat%d" % n)
        if table[-1] != 0:
            die("Pcat%d: the RFC terminates the row with 0" % n)
    expect_shape(dc, [DC_QLOOKUP_LEN], "dc_qlookup")
    expect_bytes(dc, "dc_qlookup")

    parts = [
        LICENSE,
        "\n",
        BANNER,
        "#ifndef GIMG_WEBP_VP8_PROBA_INC\n#define GIMG_WEBP_VP8_PROBA_INC\n\n",
        "enum { GIMG_VP8_NUM_TYPES = 4, GIMG_VP8_NUM_BANDS = 8, "
        "GIMG_VP8_NUM_CTX = 3,\n       GIMG_VP8_NUM_PROBAS = 11 };\n\n",
        emit_array(
            "gimg_vp8_coeffs_proba0",
            ["GIMG_VP8_NUM_TYPES", "GIMG_VP8_NUM_BANDS", "GIMG_VP8_NUM_CTX",
             "GIMG_VP8_NUM_PROBAS"],
            default),
        "\n",
        emit_array(
            "gimg_vp8_coeffs_update_proba",
            ["GIMG_VP8_NUM_TYPES", "GIMG_VP8_NUM_BANDS", "GIMG_VP8_NUM_CTX",
             "GIMG_VP8_NUM_PROBAS"],
            update),
        "\n",
        emit_array("gimg_vp8_bands", ["16"], bands),
        "\n",
    ]
    for n, table in enumerate(pcats, start=1):
        parts.append(emit_array("gimg_vp8_pcat%d" % n, [str(len(table))], table))
        parts.append("\n")
    parts.append(emit_array("gimg_vp8_dc_qlookup", [str(DC_QLOOKUP_LEN)], dc))
    parts.append("\n#endif\n")
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rfc", default=DEFAULT_RFC)
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args()
    if not os.path.isfile(args.rfc):
        die("no RFC text at %s; run tools/webp/fetch_rfc6386.sh" % args.rfc)
    text = load_rfc(args.rfc)
    out_path = os.path.join(args.out, "webp_vp8_proba.inc")
    os.makedirs(args.out, exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(generate(text))


if __name__ == "__main__":
    main()
