/**
 * @file
 *
 * PNG decode tests: DEFLATE, filters, raster output. Uses reference files
 * from tests/data/png/ (generated by tests/data/png/generate.py).
 *
 * Copyright 2026 by Corey Pennycuff
 */

#include <cstdint>
#include <cstring>
#include <ghoti.io/image/codec.h>
#include <ghoti.io/image/color.h>
#include <ghoti.io/image/core.h>
#include <ghoti.io/image/doc.h>
#include <ghoti.io/image/meta.h>
#include <ghoti.io/image/raster.h>
#include <ghoti.io/image/stream.h>
#include <string>
#include <gtest/gtest.h>
#include <vector>

#include "png_test_utils.h"
#include <array>
#include <fstream>

namespace {

const unsigned char kPngSignature[] = {
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A};

// IHDR: 1x1 grayscale 8-bit.
const unsigned char kIhdr1x1[] = {0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44,
    0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x00, 0x00,
    0x00, 0x00, 0x3A, 0x7E, 0x9B, 0x55};

const unsigned char kIendChunk[] = {
    0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82};

void append(std::vector<uint8_t> & out, const unsigned char * p, size_t n) {
  out.insert(out.end(), p, p + n);
}

/** PNG eXIf chunk type (for meta_raw tag). */
static constexpr uint32_t kPngChunk_eXIf = 0x65584966u;

} // namespace

TEST(PngDecode, DecodeNoIdatReturnsFormat) {
  // Minimal PNG (signature + IHDR + IEND, no IDAT). Decode should fail.
  std::vector<uint8_t> buf;
  append(buf, kPngSignature, sizeof(kPngSignature));
  append(buf, kIhdr1x1, sizeof(kIhdr1x1));
  append(buf, kIendChunk, sizeof(kIendChunk));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Item * item = gimg_doc_item(doc, 0);
  ASSERT_NE(item, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(item, nullptr, &raster);
  EXPECT_EQ(r, GIMG_ERR_FORMAT) << "decode with no IDAT should return FORMAT";
  EXPECT_EQ(raster, nullptr);

  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeEmptyIdatReturnsCorrupt) {
  // Minimal PNG with IDAT that decompresses to 0 bytes (empty stored block).
  const unsigned char kIdatEmpty[] = {0x00, 0x00, 0x00, 0x05, 0x49, 0x44, 0x41,
      0x54, 0x01, 0x00, 0x00, 0xFF, 0xFF, 0xCF, 0xCA, 0x62, 0x86};
  std::vector<uint8_t> buf;
  append(buf, kPngSignature, sizeof(kPngSignature));
  append(buf, kIhdr1x1, sizeof(kIhdr1x1));
  append(buf, kIdatEmpty, sizeof(kIdatEmpty));
  append(buf, kIendChunk, sizeof(kIendChunk));

  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  GIMG_Result r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Item * item = gimg_doc_item(doc, 0);
  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(item, nullptr, &raster);
  EXPECT_EQ(r, GIMG_ERR_CORRUPT) << "empty IDAT decompress should be corrupt";
  EXPECT_EQ(raster, nullptr);

  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, Decode1x1GrayFromFile) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_1x1_gray.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_GRAY);
  EXPECT_EQ(gimg_raster_bytes_per_pixel(gimg_raster_format(raster)), 1u);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0) << "1x1 gray black pixel";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, Decode1x1PaletteWithTrnsFromFile) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_1x1_palette.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_RGBA);
  EXPECT_EQ(gimg_raster_bytes_per_pixel(gimg_raster_format(raster)), 4u);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0x11);
  EXPECT_EQ(px[1], 0x22);
  EXPECT_EQ(px[2], 0x33);
  EXPECT_EQ(px[3], 0x80) << "tRNS alpha for palette index 0";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, Decode16bitGrayFromFile) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_16bit_gray.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_GRAY);
  EXPECT_EQ(gimg_raster_format(raster)->bits_per_channel[0], 16);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0x34) << "16-bit gray low byte 0x1234";
  EXPECT_EQ(px[1], 0x12) << "16-bit gray high byte";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, Decode1x1RgbaFromFile) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_1x1_rgba.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_RGBA);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0x11);
  EXPECT_EQ(px[1], 0x22);
  EXPECT_EQ(px[2], 0x33);
  EXPECT_EQ(px[3], 0x80);

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeSrgbSetsColorInfo) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_srgb.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  const GIMG_Color_Info * info = gimg_raster_color_info_const(raster);
  ASSERT_NE(info, nullptr);
  EXPECT_EQ(info->primaries, GIMG_PRIMARIES_SRGB);
  EXPECT_EQ(info->transfer, GIMG_TRANSFER_SRGB);
  EXPECT_EQ(info->intent, GIMG_INTENT_PERCEPTUAL) << "sRGB chunk intent 0 = Perceptual";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeExifAttachedToMetaRaw) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_exif.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Meta_Raw * raw = gimg_doc_meta_raw(doc);
  ASSERT_NE(raw, nullptr) << "eXIf chunk should attach doc meta_raw";

  size_t size = 0;
  r = gimg_meta_raw_get(raw, "png", kPngChunk_eXIf, nullptr, &size);
  ASSERT_EQ(r, GIMG_OK);
  EXPECT_EQ(size, 6u) << "eXIf payload in generate.py is 6 bytes";

  std::vector<uint8_t> exif_buf(size);
  r = gimg_meta_raw_get(raw, "png", kPngChunk_eXIf, exif_buf.data(), &size);
  ASSERT_EQ(r, GIMG_OK);
  EXPECT_EQ(size, 6u);
  EXPECT_EQ(exif_buf[0], 0x00);
  EXPECT_EQ(exif_buf[5], 0x05);

  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeExifPopulatesMetaCommonOrientation) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_exif_orientation.png", buf))
      << "Run tests/data/png/generate.py";
  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);
  gimg_stream_destroy(s);
  GIMG_Meta_Common * meta = gimg_doc_meta_common(doc);
  ASSERT_NE(meta, nullptr) << "eXIf with orientation should populate doc meta_common";
  EXPECT_EQ(gimg_meta_common_orientation(meta), GIMG_ORIENTATION_ROTATE_90_CW)
      << "png_exif_orientation.png has Orientation tag 6 (90 CW)";
  gimg_doc_destroy(doc);
}

TEST(PngDecode, DecodeIccpSetsColorInfo) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_iccp.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  const GIMG_Color_Info * info = gimg_raster_color_info_const(raster);
  ASSERT_NE(info, nullptr);
  EXPECT_GT(info->icc_size, 0u) << "iCCP decompressed profile attached to raster";
  EXPECT_NE(info->icc_bytes, nullptr);

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ApngTwoFramesLoadAndDecode) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_apng_2frame.png", buf))
      << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  EXPECT_EQ(gimg_doc_item_count(doc), 2u) << "APNG has 2 frames";

  GIMG_Item * item0 = gimg_doc_item(doc, 0);
  GIMG_Item * item1 = gimg_doc_item(doc, 1);
  ASSERT_NE(item0, nullptr);
  ASSERT_NE(item1, nullptr);

  uint16_t num = 0;
  uint16_t den = 0;
  gimg_item_frame_delay(item0, &num, &den);
  EXPECT_EQ(num, 50u) << "frame 0 delay_num";
  EXPECT_EQ(den, 100u) << "frame 0 delay_den";
  EXPECT_EQ(gimg_item_dispose_op(item0), GIMG_DISPOSE_NONE);
  EXPECT_EQ(gimg_item_blend_op(item0), GIMG_BLEND_SOURCE);

  gimg_item_frame_delay(item1, &num, &den);
  EXPECT_EQ(num, 25u) << "frame 1 delay_num";
  EXPECT_EQ(den, 100u) << "frame 1 delay_den";
  EXPECT_EQ(gimg_item_dispose_op(item1), GIMG_DISPOSE_BACKGROUND);
  EXPECT_EQ(gimg_item_blend_op(item1), GIMG_BLEND_OVER);

  GIMG_Raster * raster0 = nullptr;
  r = gimg_item_decode(item0, nullptr, &raster0);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster0, nullptr);
  EXPECT_EQ(gimg_raster_width(raster0), 1u);
  EXPECT_EQ(gimg_raster_height(raster0), 1u);
  const unsigned char * px0 =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster0));
  ASSERT_NE(px0, nullptr);
  EXPECT_EQ(px0[0], 0) << "frame 0 is black (gray 0)";

  GIMG_Raster * raster1 = nullptr;
  r = gimg_item_decode(item1, nullptr, &raster1);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster1, nullptr);
  EXPECT_EQ(gimg_raster_width(raster1), 1u);
  EXPECT_EQ(gimg_raster_height(raster1), 1u);
  const unsigned char * px1 =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster1));
  ASSERT_NE(px1, nullptr);
  EXPECT_EQ(px1[0], 0x80) << "frame 1 is gray 0x80";

  gimg_raster_destroy(raster0);
  gimg_raster_destroy(raster1);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ApngThreeFramesLoadAndDecode) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_apng_3frame.png", buf))
      << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);
  gimg_stream_destroy(s);
  s = nullptr;

  EXPECT_EQ(gimg_doc_item_count(doc), 3u);

  uint16_t num = 0, den = 0;
  GIMG_Item * item0 = gimg_doc_item((GIMG_Doc *)doc, 0);
  GIMG_Item * item1 = gimg_doc_item((GIMG_Doc *)doc, 1);
  GIMG_Item * item2 = gimg_doc_item((GIMG_Doc *)doc, 2);
  ASSERT_NE(item0, nullptr);
  ASSERT_NE(item1, nullptr);
  ASSERT_NE(item2, nullptr);

  gimg_item_frame_delay(item0, &num, &den);
  EXPECT_EQ(num, 50u);
  EXPECT_EQ(den, 100u);
  EXPECT_EQ(gimg_item_dispose_op(item0), GIMG_DISPOSE_NONE);
  EXPECT_EQ(gimg_item_blend_op(item0), GIMG_BLEND_SOURCE);

  gimg_item_frame_delay(item1, &num, &den);
  EXPECT_EQ(num, 25u);
  EXPECT_EQ(den, 100u);
  EXPECT_EQ(gimg_item_dispose_op(item1), GIMG_DISPOSE_BACKGROUND);
  EXPECT_EQ(gimg_item_blend_op(item1), GIMG_BLEND_OVER);

  gimg_item_frame_delay(item2, &num, &den);
  EXPECT_EQ(num, 10u);
  EXPECT_EQ(den, 100u);
  EXPECT_EQ(gimg_item_dispose_op(item2), GIMG_DISPOSE_PREVIOUS);
  EXPECT_EQ(gimg_item_blend_op(item2), GIMG_BLEND_OVER);

  GIMG_Raster * r0 = nullptr;
  GIMG_Raster * r1 = nullptr;
  GIMG_Raster * r2 = nullptr;
  r = gimg_item_decode(item0, nullptr, &r0);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(r0, nullptr);
  r = gimg_item_decode(item1, nullptr, &r1);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(r1, nullptr);
  r = gimg_item_decode(item2, nullptr, &r2);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(r2, nullptr);

  EXPECT_EQ(static_cast<const unsigned char *>(gimg_raster_pixels_const(r0))[0],
            0);
  EXPECT_EQ(static_cast<const unsigned char *>(gimg_raster_pixels_const(r1))[0],
            0x80);
  EXPECT_EQ(static_cast<const unsigned char *>(gimg_raster_pixels_const(r2))[0],
            0xC0);

  gimg_raster_destroy(r0);
  gimg_raster_destroy(r1);
  gimg_raster_destroy(r2);
  gimg_doc_destroy(doc);
}

TEST(PngDecode, ApngTruncatedReturnsErrorNoCrash) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_apng_2frame.png", buf));

  // Truncate before IEND (e.g. remove last 20 bytes). Load should fail.
  if (buf.size() > 20) {
    buf.resize(buf.size() - 20);
  }
  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  EXPECT_NE(r, GIMG_OK);
  EXPECT_EQ(doc, nullptr);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ApngInvalidSignatureRejected) {
  // Not a PNG signature: load should fail with FORMAT or similar.
  std::vector<uint8_t> buf = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  EXPECT_NE(r, GIMG_OK);
  EXPECT_EQ(doc, nullptr);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ApngMaxFrameCountLimitEnforced) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_apng_2frame.png", buf));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Limits limits = {};
  limits.max_frame_count = 1;
  GIMG_Load_Options opts = {};
  opts.limits = &limits;
  opts.strictness = GIMG_NORMAL;

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, &opts, nullptr, &doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(r, GIMG_ERR_LIMIT) << "acTL num_frames=2 exceeds max_frame_count=1";
  EXPECT_EQ(doc, nullptr);
}

TEST(PngDecode, ApngMaxChunkSizeLimitEnforced) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_1x1_gray.png", buf));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Limits limits = {};
  limits.max_chunk_size = 8;  // IHDR payload is 13 bytes
  GIMG_Load_Options opts = {};
  opts.limits = &limits;
  opts.strictness = GIMG_NORMAL;

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, &opts, nullptr, &doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(r, GIMG_ERR_LIMIT) << "IHDR length 13 exceeds max_chunk_size=8";
  EXPECT_EQ(doc, nullptr);
}

// PNG checks max_decoded_pixels only when decoding - png_load enforces
// max_chunk_size and max_frame_count, but never the pixel count - so a limit
// set at load time has to survive the load to bound anything at all.
TEST(PngDecode, LoadLimitsBoundALaterDecodeWithNoOptions) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_2x2_gray.png", buf));
  GIMG_Stream * s = nullptr;
  ASSERT_EQ(gimg_stream_create_memory(buf.data(), buf.size(), &s), GIMG_OK);
  GIMG_Limits limits = {};
  limits.max_decoded_pixels = 1;  // 2x2 = 4 pixels
  GIMG_Load_Options lopts = {};
  lopts.limits = &limits;
  GIMG_Doc * doc = nullptr;
  GIMG_Result r = gimg_doc_load(s, &lopts, nullptr, &doc);
  gimg_stream_destroy(s);
  ASSERT_EQ(r, GIMG_OK) << "png_load does not cap pixels, so the load succeeds";
  ASSERT_NE(doc, nullptr);
  GIMG_Raster * raster = nullptr;
  // No decode options: the limit must still be the one given at load.
  EXPECT_EQ(gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster),
      GIMG_ERR_LIMIT);
  EXPECT_EQ(raster, nullptr);
  gimg_doc_destroy(doc);
}

// png_save re-decodes its source item when the document holds no raster, and
// it has no decode options to hand on.  That decode used to run with no limits
// at all, so saving was a way around a cap the application had set: a 20-byte
// IHDR naming an enormous canvas allocates on the way out, and png_load will
// not have stopped it because it does not look at the pixel count.
TEST(PngDecode, SaveHonoursTheLimitsTheDocumentWasLoadedWith) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_2x2_gray.png", buf));
  GIMG_Stream * s = nullptr;
  ASSERT_EQ(gimg_stream_create_memory(buf.data(), buf.size(), &s), GIMG_OK);
  GIMG_Limits limits = {};
  limits.max_decoded_pixels = 1;
  GIMG_Load_Options lopts = {};
  lopts.limits = &limits;
  GIMG_Doc * doc = nullptr;
  GIMG_Result r = gimg_doc_load(s, &lopts, nullptr, &doc);
  gimg_stream_destroy(s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);
  GIMG_Stream * out = nullptr;
  ASSERT_EQ(gimg_stream_create_memory_output(&out), GIMG_OK);
  GIMG_Save_Options sopts = {};
  GIMG_Save_Report report = {};
  EXPECT_NE(gimg_doc_save(doc, out, "png", &sopts, &report), GIMG_OK)
      << "a save must not decode past the limit the document was loaded with";
  gimg_stream_destroy(out);
  gimg_doc_destroy(doc);
}

TEST(PngDecode, MaxDecodedPixelsLimitEnforced) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_2x2_gray.png", buf));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  gimg_stream_destroy(s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Limits limits = {};
  limits.max_decoded_pixels = 1;  // 2x2 = 4 pixels
  GIMG_Decode_Options decode_opts = {};
  decode_opts.limits = &limits;
  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), &decode_opts, &raster);
  gimg_doc_destroy(doc);
  EXPECT_EQ(r, GIMG_ERR_LIMIT) << "2x2 pixel count exceeds max_decoded_pixels=1";
  EXPECT_EQ(raster, nullptr);
}

TEST(PngDecode, LimitEnforcedMaxFrameCountFillsDiagnostics) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_apng_2frame.png", buf));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Limits limits = {};
  limits.max_frame_count = 1;
  GIMG_Load_Options opts = {};
  opts.limits = &limits;
  opts.strictness = GIMG_NORMAL;

  GIMG_Diagnostics diag = {nullptr, 0, 0, nullptr};
  gimg_diagnostics_init(&diag, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, &opts, &diag, &doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(r, GIMG_ERR_LIMIT);
  EXPECT_EQ(doc, nullptr);
  EXPECT_GE(diag.count, 1u) << "diagnostics should report the limit";
  if (diag.count >= 1u && diag.items[0].recommended_action) {
    std::string action(diag.items[0].recommended_action);
    EXPECT_NE(action.find("max_frame_count"), std::string::npos)
        << "recommended_action should mention max_frame_count";
  }
  gimg_diagnostics_destroy(&diag);
}

// ---- Golden-file decode tests: canonical pixel hash per reference file ----

TEST(PngDecode, Golden1x1Gray) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_1x1_gray.png", buf));
  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  uint64_t hash = png_test::raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 12638153115695167455ULL) << "canonical pixel hash 1x1 gray";
}

TEST(PngDecode, Golden1x1Palette) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_1x1_palette.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = png_test::raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 15243095932836669713ULL) << "canonical pixel hash 1x1 palette+tRNS";
}

TEST(PngDecode, Golden16bitGray) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_16bit_gray.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = png_test::raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 571567958656141443ULL) << "canonical pixel hash 16-bit gray";
}

TEST(PngDecode, Golden1x1Rgba) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_1x1_rgba.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = png_test::raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 15243095932836669713ULL) << "canonical pixel hash 1x1 RGBA";
}

TEST(PngDecode, Golden16bitRgba) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_16bit_rgba.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = png_test::raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 1173251487157325173ULL) << "canonical pixel hash 16-bit RGBA";
}

TEST(PngDecode, GoldenSrgb) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_srgb.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = png_test::raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 12638153115695167455ULL) << "canonical pixel hash sRGB (same pixels as 1x1 gray)";
}

TEST(PngDecode, GoldenExif) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_exif.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = png_test::raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 12638153115695167455ULL) << "canonical pixel hash eXIf (same pixels as 1x1 gray)";
}

TEST(PngDecode, GoldenIccp) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_iccp.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = png_test::raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 12638153115695167455ULL) << "canonical pixel hash iCCP (same pixels as 1x1 gray)";
}

TEST(PngDecode, GoldenApng2Frame) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_apng_2frame.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(gimg_doc_item_count(doc), 2u);
  uint64_t hash0 = 0, hash1 = 0;
  GIMG_Raster * r0 = nullptr;
  GIMG_Raster * r1 = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &r0);
  gimg_item_decode(gimg_doc_item(doc, 1), nullptr, &r1);
  hash0 = png_test::raster_pixel_hash(r0);
  hash1 = png_test::raster_pixel_hash(r1);
  gimg_raster_destroy(r0);
  gimg_raster_destroy(r1);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash0, 12638153115695167455ULL) << "APNG frame 0 pixel hash";
  EXPECT_EQ(hash1, 12638293853183578463ULL) << "APNG frame 1 pixel hash";
}

TEST(PngDecode, GoldenApng3Frame) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_apng_3frame.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(gimg_doc_item_count(doc), 3u);
  GIMG_Raster * r0 = nullptr;
  GIMG_Raster * r1 = nullptr;
  GIMG_Raster * r2 = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &r0);
  gimg_item_decode(gimg_doc_item(doc, 1), nullptr, &r1);
  gimg_item_decode(gimg_doc_item(doc, 2), nullptr, &r2);
  uint64_t h0 = png_test::raster_pixel_hash(r0);
  uint64_t h1 = png_test::raster_pixel_hash(r1);
  uint64_t h2 = png_test::raster_pixel_hash(r2);
  gimg_raster_destroy(r0);
  gimg_raster_destroy(r1);
  gimg_raster_destroy(r2);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(h0, 12638153115695167455ULL) << "APNG 3-frame: frame 0";
  EXPECT_EQ(h1, 12638293853183578463ULL) << "APNG 3-frame: frame 1";
  EXPECT_EQ(h2, 12638364221927783967ULL) << "APNG 3-frame: frame 2";
}

TEST(PngDecode, GoldenApng16bitRgbaBlend) {
  // 2-frame APNG 16-bit RGBA: frame 0 black opaque, frame 1 red 50% OVER.
  // Expected pixels are spec-correct 16-bit values written by generate.py
  // (frame 0 black opaque, frame 1 composited OVER); no blend logic in the test.
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_apng_2frame_16bit_rgba.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(gimg_doc_item_count(doc), 2u);
  GIMG_Raster * r0 = nullptr;
  GIMG_Raster * r1 = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &r0);
  gimg_item_decode(gimg_doc_item(doc, 1), nullptr, &r1);
  ASSERT_NE(r0, nullptr);
  ASSERT_NE(r1, nullptr);
  ASSERT_EQ(gimg_raster_width(r0), 1u);
  ASSERT_EQ(gimg_raster_height(r0), 1u);
  ASSERT_EQ(gimg_raster_width(r1), 1u);
  ASSERT_EQ(gimg_raster_height(r1), 1u);
  const unsigned char * p0 =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(r0));
  const unsigned char * p1 =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(r1));
  ASSERT_NE(p0, nullptr);
  ASSERT_NE(p1, nullptr);
  // Load expected pixels from oracle (16 bytes: frame0 then frame1, RGBA 16-bit LE).
  // Oracle is Pillow; it returns 8-bit for 16-bit PNG so we allow per-component
  // tolerance to account for 8- vs 16-bit rounding (one 8-bit step ≈ 257 in 16-bit).
  std::string oracle_path =
      std::string(GIMG_TEST_DATA_PNG) + "/png_apng_2frame_16bit_rgba_expected.bin";
  std::ifstream oracle_file(oracle_path, std::ios::binary);
  ASSERT_TRUE(oracle_file) << "expected file: run python3 tests/data/png/generate.py (requires Pillow)";
  std::array<uint8_t, 16> expected_bytes;
  ASSERT_TRUE(oracle_file.read(reinterpret_cast<char *>(expected_bytes.data()), 16));
  oracle_file.close();
  const auto * expected0 = reinterpret_cast<const uint16_t *>(expected_bytes.data());
  const auto * expected1 = reinterpret_cast<const uint16_t *>(expected_bytes.data() + 8);
  const auto * dec0 = reinterpret_cast<const uint16_t *>(p0);
  const auto * dec1 = reinterpret_cast<const uint16_t *>(p1);
  // One 8-bit step in 16-bit ≈ 257. Alpha can differ more with Pillow (e.g. 191 vs 255).
  constexpr uint16_t kToleranceRGB = 257u;
  constexpr uint16_t kToleranceA = 20000u;  // allow Pillow alpha quirk (8-bit rounded)
  for (size_t c = 0; c < 4; c++) {
    uint16_t tol = (c == 3) ? kToleranceA : kToleranceRGB;
    EXPECT_NEAR(static_cast<double>(dec0[c]), static_cast<double>(expected0[c]),
                static_cast<double>(tol))
        << "frame 0 component " << c << " (RGBA)";
  }
  for (size_t c = 0; c < 4; c++) {
    uint16_t tol = (c == 3) ? kToleranceA : kToleranceRGB;
    EXPECT_NEAR(static_cast<double>(dec1[c]), static_cast<double>(expected1[c]),
                static_cast<double>(tol))
        << "frame 1 component " << c << " (RGBA)";
  }
  EXPECT_EQ(png_test::raster_pixel_hash(r0), 12289102041121930043ULL)
      << "frame 0 hash (documented)";
  EXPECT_EQ(png_test::raster_pixel_hash(r1), 18296124214518667195ULL)
      << "frame 1 hash (documented)";
  gimg_raster_destroy(r0);
  gimg_raster_destroy(r1);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

int main(int argc, char ** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}

// ---------------------------------------------------------------------------
// Sample depths below 8 bits, crossed with Adam7 interlacing.
//
// PNG 7.2 packs samples of depth 1, 2 and 4 several to a byte, MSB first, each
// scanline padded to a byte boundary. Adam7 (PNG 8.2) then splits the image
// into seven passes of independently padded scanlines. Pixel i of a pass row
// belongs at image column x_offset + i * x_step, which below 8 bits is a *bit*
// position; treating it as a byte position both corrupts memory and misplaces
// every sample. The fixtures come in interlaced and non-interlaced pairs built
// from one sample array by tests/data/png/generate.py, with the expected
// pixels in a .raw file computed from PNG 13.12's rescaling rule.
// ---------------------------------------------------------------------------

namespace {

struct SubByteCase {
  const char * base;  ///< Fixture stem, e.g. "png_gray1_32x8".
  uint32_t width;
  uint32_t height;
  bool palette;       ///< Palette decodes to RGBA8; grayscale to GRAY8.
};

const SubByteCase kSubByteCases[] = {
    {"png_gray1_32x8", 32, 8, false},
    {"png_gray2_32x8", 32, 8, false},
    {"png_gray4_32x8", 32, 8, false},
    {"png_pal1_32x8", 32, 8, true},
    {"png_pal2_32x8", 32, 8, true},
    {"png_pal4_32x8", 32, 8, true},
    {"png_gray1_33x9", 33, 9, false},
    {"png_gray2_33x9", 33, 9, false},
    {"png_gray4_33x9", 33, 9, false},
    {"png_pal1_33x9", 33, 9, true},
    {"png_pal2_33x9", 33, 9, true},
    {"png_pal4_33x9", 33, 9, true},
};

/** Decode a fixture by name. Caller destroys *out_raster, *out_doc, *out_s. */
::testing::AssertionResult DecodeFixture(const char * filename,
    GIMG_Stream ** out_s, GIMG_Doc ** out_doc, GIMG_Raster ** out_raster) {
  std::vector<uint8_t> buf;
  if (!png_test::load_png_file(filename, buf)) {
    return ::testing::AssertionFailure()
        << filename << " missing; run tests/data/png/generate.py";
  }
  GIMG_Stream * s = nullptr;
  if (gimg_stream_create_memory(buf.data(), buf.size(), &s) != GIMG_OK) {
    return ::testing::AssertionFailure() << "stream create failed";
  }
  GIMG_Doc * doc = nullptr;
  GIMG_Result r = gimg_doc_load(s, nullptr, nullptr, &doc);
  if (r != GIMG_OK) {
    gimg_stream_destroy(s);
    return ::testing::AssertionFailure()
        << "load " << filename << " failed: " << static_cast<int>(r);
  }
  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  if (r != GIMG_OK) {
    gimg_doc_destroy(doc);
    gimg_stream_destroy(s);
    return ::testing::AssertionFailure()
        << "decode " << filename << " failed: " << static_cast<int>(r);
  }
  *out_s = s;
  *out_doc = doc;
  *out_raster = raster;
  return ::testing::AssertionSuccess();
}

/** Copy a raster's pixels without stride padding. */
std::vector<uint8_t> RasterBytes(const GIMG_Raster * raster) {
  const GIMG_Pixel_Format * fmt = gimg_raster_format(raster);
  size_t bpp = gimg_raster_bytes_per_pixel(fmt);
  uint32_t w = gimg_raster_width(raster);
  uint32_t h = gimg_raster_height(raster);
  size_t stride = gimg_raster_stride_bytes(raster);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  std::vector<uint8_t> out;
  out.reserve(static_cast<size_t>(w) * h * bpp);
  for (uint32_t y = 0; y < h; y++) {
    out.insert(out.end(), px + static_cast<size_t>(y) * stride,
        px + static_cast<size_t>(y) * stride + static_cast<size_t>(w) * bpp);
  }
  return out;
}

} // namespace

TEST(PngDecode, SubByteDepthsDecodeToTheSamplesTheSpecScalesThemTo) {
  for (const SubByteCase & c : kSubByteCases) {
    std::vector<uint8_t> expected;
    ASSERT_TRUE(png_test::load_png_file(
        (std::string(c.base) + ".raw").c_str(), expected))
        << c.base << ".raw missing; run tests/data/png/generate.py";

    GIMG_Stream * s = nullptr;
    GIMG_Doc * doc = nullptr;
    GIMG_Raster * raster = nullptr;
    ASSERT_TRUE(DecodeFixture(
        (std::string(c.base) + ".png").c_str(), &s, &doc, &raster));

    EXPECT_EQ(gimg_raster_width(raster), c.width) << c.base;
    EXPECT_EQ(gimg_raster_height(raster), c.height) << c.base;
    const GIMG_Pixel_Format * fmt = gimg_raster_format(raster);
    // PNG 4.5.5: a palette entry is RGB, so an indexed image decodes to
    // colour; a grayscale image of any depth below 8 rescales to GRAY8.
    EXPECT_EQ(fmt->channel_model,
        c.palette ? GIMG_CHANNEL_RGBA : GIMG_CHANNEL_GRAY)
        << c.base;
    EXPECT_EQ(RasterBytes(raster), expected) << c.base;

    gimg_raster_destroy(raster);
    gimg_doc_destroy(doc);
    gimg_stream_destroy(s);
  }
}

TEST(PngDecode, Adam7IsAReorderingSoInterlacedDecodesLikeNonInterlaced) {
  // PNG 8.2: interlacing changes the transmission order of the pixels and
  // nothing else. The two members of each fixture pair hold the same samples,
  // so whatever the decoder produces for one it must produce for the other.
  // This needs no reference decoder to check.
  for (const SubByteCase & c : kSubByteCases) {
    GIMG_Stream * s_plain = nullptr;
    GIMG_Doc * doc_plain = nullptr;
    GIMG_Raster * plain = nullptr;
    ASSERT_TRUE(DecodeFixture(
        (std::string(c.base) + ".png").c_str(), &s_plain, &doc_plain, &plain));

    GIMG_Stream * s_int = nullptr;
    GIMG_Doc * doc_int = nullptr;
    GIMG_Raster * interlaced = nullptr;
    ASSERT_TRUE(DecodeFixture((std::string(c.base) + "_interlaced.png").c_str(),
        &s_int, &doc_int, &interlaced));

    EXPECT_TRUE(png_test::rasters_equal(plain, interlaced))
        << c.base << ": Adam7 pass reassembly disagrees with the "
        << "non-interlaced encoding of the same samples";

    gimg_raster_destroy(interlaced);
    gimg_doc_destroy(doc_int);
    gimg_stream_destroy(s_int);
    gimg_raster_destroy(plain);
    gimg_doc_destroy(doc_plain);
    gimg_stream_destroy(s_plain);
  }
}

TEST(PngDecode, SubByteInterlacedDecodesToTheExpectedSamples) {
  // The pair test above would pass if both halves were wrong in the same way;
  // this one pins the interlaced half to the spec-derived expected pixels.
  for (const SubByteCase & c : kSubByteCases) {
    std::vector<uint8_t> expected;
    ASSERT_TRUE(png_test::load_png_file(
        (std::string(c.base) + ".raw").c_str(), expected))
        << c.base << ".raw missing; run tests/data/png/generate.py";

    GIMG_Stream * s = nullptr;
    GIMG_Doc * doc = nullptr;
    GIMG_Raster * raster = nullptr;
    ASSERT_TRUE(DecodeFixture((std::string(c.base) + "_interlaced.png").c_str(),
        &s, &doc, &raster));

    EXPECT_EQ(RasterBytes(raster), expected) << c.base << " interlaced";

    gimg_raster_destroy(raster);
    gimg_doc_destroy(doc);
    gimg_stream_destroy(s);
  }
}

// ---------------------------------------------------------------------------
// zlib wrapper integrity (PNG 10.3, RFC 1950).
//
// PNG carries two independent checks on every compressed payload: the chunk
// CRC over the stored bytes, and the Adler-32 over the *uncompressed* bytes at
// the end of the zlib stream. The second is the only one that catches a stream
// which still inflates but to the wrong data, so skipping the two header bytes
// and four trailer bytes without reading them leaves half the check in place.
// The fixtures have correct chunk CRCs and differ from png_zlib_ok.png only in
// the zlib wrapper.
// ---------------------------------------------------------------------------

TEST(PngDecode, ZlibWrapperIsCheckedNotSkipped) {
  struct Case {
    const char * filename;
    GIMG_Result expect;
    const char * why;
  };
  const Case cases[] = {
      {"png_zlib_ok.png", GIMG_OK, "control: a correct zlib stream"},
      {"png_zlib_bad_adler.png", GIMG_ERR_CORRUPT,
          "Adler-32 of the wrong bytes (RFC 1950 2.2); DEFLATE alone accepts it"},
      {"png_zlib_bad_header.png", GIMG_ERR_FORMAT,
          "CMF/FLG not a multiple of 31 and method 9, not the 8 PNG 10.3 allows"},
      {"png_zlib_preset_dict.png", GIMG_ERR_FORMAT,
          "FDICT set, which PNG 10.3 forbids and which shifts the DEFLATE data"},
  };
  for (const Case & c : cases) {
    std::vector<uint8_t> buf;
    ASSERT_TRUE(png_test::load_png_file(c.filename, buf))
        << c.filename << " missing; run tests/data/png/generate.py";
    GIMG_Stream * s = nullptr;
    ASSERT_EQ(gimg_stream_create_memory(buf.data(), buf.size(), &s), GIMG_OK);
    GIMG_Doc * doc = nullptr;
    GIMG_Result r = gimg_doc_load(s, nullptr, nullptr, &doc);
    GIMG_Raster * raster = nullptr;
    if (r == GIMG_OK) {
      r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
    }
    EXPECT_EQ(r, c.expect) << c.filename << ": " << c.why;
    if (raster) {
      gimg_raster_destroy(raster);
    }
    if (doc) {
      gimg_doc_destroy(doc);
    }
    gimg_stream_destroy(s);
  }
}

// ---------------------------------------------------------------------------
// A suggested palette on a truecolour image (PNG 11.2.2).
//
// PLTE is required for colour type 3 and "shall not appear" for colour types 0
// and 4, but for 2 and 6 it may appear as a suggested palette for a viewer that
// cannot display truecolour. A decoder that can display truecolour ignores it.
// The published conformance suite carries two such files (pp0n2c16, pp0n6a08).
// ---------------------------------------------------------------------------

TEST(PngDecode, SuggestedPaletteOnTruecolourIsAcceptedAndIgnored) {
  // The palette in the fixture does not contain the image's colours, so a
  // decoder that used it would produce different pixels from the twin that
  // carries no PLTE. Comparing the two needs no reference decoder.
  GIMG_Stream * s_with = nullptr;
  GIMG_Doc * doc_with = nullptr;
  GIMG_Raster * with_palette = nullptr;
  ASSERT_TRUE(DecodeFixture(
      "png_rgb_suggested_palette.png", &s_with, &doc_with, &with_palette));

  GIMG_Stream * s_without = nullptr;
  GIMG_Doc * doc_without = nullptr;
  GIMG_Raster * without_palette = nullptr;
  ASSERT_TRUE(DecodeFixture(
      "png_rgb_no_palette.png", &s_without, &doc_without, &without_palette));

  EXPECT_TRUE(png_test::rasters_equal(with_palette, without_palette))
      << "a suggested palette is advisory and must not change the pixels";

  gimg_raster_destroy(without_palette);
  gimg_doc_destroy(doc_without);
  gimg_stream_destroy(s_without);
  gimg_raster_destroy(with_palette);
  gimg_doc_destroy(doc_with);
  gimg_stream_destroy(s_with);

  // Colour type 6 may carry one too.
  GIMG_Stream * s_rgba = nullptr;
  GIMG_Doc * doc_rgba = nullptr;
  GIMG_Raster * rgba = nullptr;
  EXPECT_TRUE(DecodeFixture(
      "png_rgba_suggested_palette.png", &s_rgba, &doc_rgba, &rgba));
  if (rgba) {
    gimg_raster_destroy(rgba);
    gimg_doc_destroy(doc_rgba);
    gimg_stream_destroy(s_rgba);
  }
}

TEST(PngDecode, PaletteOnGrayscaleIsRejected) {
  // PNG 11.2.2: "This chunk shall not appear for colour types 0 and 4." Some
  // decoders are more forgiving than the spec here - Pillow reads the file -
  // but a critical chunk where the spec forbids one is a malformed file, and
  // this library reports malformed files rather than guessing past them.
  std::vector<uint8_t> buf;
  ASSERT_TRUE(png_test::load_png_file("png_gray_forbidden_palette.png", buf))
      << "Run tests/data/png/generate.py";
  GIMG_Stream * s = nullptr;
  ASSERT_EQ(gimg_stream_create_memory(buf.data(), buf.size(), &s), GIMG_OK);
  GIMG_Doc * doc = nullptr;
  EXPECT_EQ(gimg_doc_load(s, nullptr, nullptr, &doc), GIMG_ERR_FORMAT);
  if (doc) {
    gimg_doc_destroy(doc);
  }
  gimg_stream_destroy(s);
}

// ---------------------------------------------------------------------------
// PNG Third Edition colour chunks.
//
// cICP carries coding-independent code points (ITU-T H.273) and the Third
// Edition puts it ahead of sRGB, iCCP and gAMA+cHRM: where it appears, it says
// what the samples mean and the others do not get a say.
//
// GIMG_Color_Info can describe sRGB, Adobe RGB, linear and a plain gamma.
// CICP names far more - BT.2020, PQ, HLG, limited range - so only the
// combinations this model holds are translated. The rest leave the colour
// unknown rather than being rounded to the nearest thing expressible, which
// would assert something about the pixels the file never said. Every one of
// these chunks is preserved on the way through regardless.
// ---------------------------------------------------------------------------

TEST(PngDecode, CicpOutranksTheOlderColourChunks) {
  // The fixture carries cICP naming the sRGB pair and a gAMA claiming 1.0.
  // Honouring the precedence and ignoring it give different answers.
  GIMG_Stream * s = nullptr;
  GIMG_Doc * doc = nullptr;
  GIMG_Raster * raster = nullptr;
  ASSERT_TRUE(DecodeFixture("png_cicp_srgb.png", &s, &doc, &raster));
  const GIMG_Color_Info * info = gimg_raster_color_info_const(raster);
  ASSERT_NE(info, nullptr);
  EXPECT_EQ(info->primaries, GIMG_PRIMARIES_SRGB);
  EXPECT_EQ(info->transfer, GIMG_TRANSFER_SRGB)
      << "cICP names the sRGB transfer; the gAMA of 1.0 must not win";
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ACicpThisColourModelCannotHoldLeavesItUnknown) {
  // BT.2020 primaries with the PQ transfer: a legal file, and nothing in
  // GIMG_Color_Info can say what it means. Reporting sRGB would be a lie.
  GIMG_Stream * s = nullptr;
  GIMG_Doc * doc = nullptr;
  GIMG_Raster * raster = nullptr;
  ASSERT_TRUE(DecodeFixture("png_cicp_bt2020_pq.png", &s, &doc, &raster));
  const GIMG_Color_Info * info = gimg_raster_color_info_const(raster);
  ASSERT_NE(info, nullptr);
  EXPECT_EQ(info->primaries, GIMG_PRIMARIES_UNKNOWN);
  EXPECT_EQ(info->transfer, GIMG_TRANSFER_UNKNOWN);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ThirdEditionChunksSurviveARoundTrip) {
  // cICP, mDCv and cLLi are content the file came with. Whether or not this
  // library can act on them, saving must not drop them.
  struct Case {
    const char * filename;
    std::vector<uint32_t> expect_types;
  };
  const uint32_t kCicp = 0x63494350u;
  const uint32_t kMdcv = 0x6D444376u;
  const uint32_t kClli = 0x634C4C69u;
  const Case cases[] = {
      {"png_cicp_srgb.png", {kCicp}},
      {"png_cicp_bt2020_pq.png", {kCicp}},
      {"png_mdcv_clli.png", {kMdcv, kClli}},
  };
  for (const Case & c : cases) {
    std::vector<uint8_t> buf;
    ASSERT_TRUE(png_test::load_png_file(c.filename, buf)) << c.filename;
    GIMG_Stream * s = nullptr;
    ASSERT_EQ(gimg_stream_create_memory(buf.data(), buf.size(), &s), GIMG_OK);
    GIMG_Doc * doc = nullptr;
    ASSERT_EQ(gimg_doc_load(s, nullptr, nullptr, &doc), GIMG_OK) << c.filename;
    gimg_stream_destroy(s);

    GIMG_Stream * out_s = nullptr;
    ASSERT_EQ(gimg_stream_create_memory_output(&out_s), GIMG_OK);
    GIMG_Save_Options opts = {};
    opts.metadata_policy = GIMG_META_PRESERVE_ALL;
    GIMG_Save_Report report = {};
    ASSERT_EQ(gimg_doc_save(doc, out_s, "png", &opts, &report), GIMG_OK)
        << c.filename;
    const void * p = nullptr;
    size_t n = 0;
    gimg_stream_output_buffer(out_s, &p, &n);
    std::vector<uint8_t> saved(static_cast<const uint8_t *>(p),
        static_cast<const uint8_t *>(p) + n);
    gimg_stream_destroy(out_s);
    gimg_doc_destroy(doc);

    // Walk the chunks of the saved file looking for each expected type.
    for (uint32_t want : c.expect_types) {
      bool found = false;
      size_t i = 8;
      while (i + 8 <= saved.size()) {
        uint32_t len = (uint32_t)saved[i] << 24 | (uint32_t)saved[i + 1] << 16 |
            (uint32_t)saved[i + 2] << 8 | (uint32_t)saved[i + 3];
        uint32_t type = (uint32_t)saved[i + 4] << 24 |
            (uint32_t)saved[i + 5] << 16 | (uint32_t)saved[i + 6] << 8 |
            (uint32_t)saved[i + 7];
        if (type == want) {
          found = true;
          break;
        }
        i += 12u + (size_t)len;
      }
      EXPECT_TRUE(found) << c.filename << " lost chunk 0x" << std::hex << want;
    }
  }
}

// ---------------------------------------------------------------------------
// Filter types (PNG clause 9, Table 9.1)
//
// Table 9.1 defines filter types 0 through 4 and nothing else. A row whose
// filter byte is above 4 cannot be reconstructed: there is no predictor to
// invert. Treating it as None - which is what "ignore what you do not know"
// amounts to here - returns success for pixels no conforming decoder produces.
// libpng calls such a file a "bad adaptive filter value" and refuses it;
// Pillow calls it "unrecognized data stream contents" and refuses it too.
// ---------------------------------------------------------------------------

namespace {

/** Load a fixture and try to decode it; returns the result of the decode. */
GIMG_Result TryDecodeFixture(const char * filename) {
  std::vector<uint8_t> buf;
  if (!png_test::load_png_file(filename, buf)) {
    return GIMG_ERR_IO;
  }
  GIMG_Stream * s = nullptr;
  if (gimg_stream_create_memory(buf.data(), buf.size(), &s) != GIMG_OK) {
    return GIMG_ERR_INTERNAL;
  }
  GIMG_Doc * doc = nullptr;
  GIMG_Result r = gimg_doc_load(s, nullptr, nullptr, &doc);
  if (r != GIMG_OK) {
    gimg_stream_destroy(s);
    return r;
  }
  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  if (raster) {
    gimg_raster_destroy(raster);
  }
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  return r;
}

} // namespace

TEST(PngFilterType, AFilterTypeTableNineOneDoesNotDefineIsRefused) {
  EXPECT_EQ(TryDecodeFixture("png_bad_filter_type.png"), GIMG_ERR_CORRUPT);
}

TEST(PngFilterType, TheSameImageWithATypeThatExistsStillDecodes) {
  // The other half of the pair. A decoder that refused every row it had not
  // seen before would pass the test above and fail this one; filter type 1 is
  // Sub, the type a rejection of "anything above 4" must not reach.
  GIMG_Stream * s = nullptr;
  GIMG_Doc * doc = nullptr;
  GIMG_Raster * raster = nullptr;
  ASSERT_TRUE(DecodeFixture("png_good_filter_type.png", &s, &doc, &raster));
  // Row 0 is stored unfiltered; row 1 is Sub over {1,1,1,1}, so each sample is
  // the running sum of the ones before it (9.2).
  const std::vector<uint8_t> expected = {10, 20, 30, 40, 1, 2, 3, 4};
  EXPECT_EQ(RasterBytes(raster), expected);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngFilterType, TheCheckIsReachedOnTheInterlacedPathToo) {
  // Adam7 filters every pass as its own image (9.2), so the filter byte is
  // read in a second place and has to be checked in both.
  EXPECT_EQ(TryDecodeFixture("png_bad_filter_type_interlaced.png"),
      GIMG_ERR_CORRUPT);
}
