/**
 * @file
 *
 * PNG decode tests: DEFLATE, filters, raster output. Uses reference files
 * from tests/data/png/ (generated by tests/data/png/generate.py) when
 * GIMG_TEST_DATA_PNG is defined.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#include <cstdint>
#include <cstring>
#include <ghoti.io/image/codec.h>
#include <ghoti.io/image/color.h>
#include <ghoti.io/image/doc.h>
#include <ghoti.io/image/meta.h>
#include <ghoti.io/image/raster.h>
#include <ghoti.io/image/stream.h>
#include <gtest/gtest.h>
#include <vector>

#ifdef GIMG_TEST_DATA_PNG
#include <fstream>
#include <string>
#endif

namespace {

const unsigned char kPngSignature[] = {
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A};

// IHDR: 1x1 grayscale 8-bit.
const unsigned char kIhdr1x1[] = {0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44,
    0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x00, 0x00,
    0x00, 0x00, 0x3A, 0x7E, 0x9B, 0x55};

const unsigned char kIendChunk[] = {
    0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82};

void append(std::vector<uint8_t> & out, const unsigned char * p, size_t n) {
  out.insert(out.end(), p, p + n);
}

#ifdef GIMG_TEST_DATA_PNG
/** Load a PNG reference file into a buffer. Returns true on success. */
bool load_png_file(const char * filename, std::vector<uint8_t> & out) {
  std::string path = std::string(GIMG_TEST_DATA_PNG) + "/" + filename;
  std::ifstream f(path, std::ios::binary | std::ios::ate);
  if (!f) {
    return false;
  }
  std::ifstream::pos_type size = f.tellg();
  if (size <= 0) {
    return false;
  }
  out.resize(static_cast<size_t>(size));
  f.seekg(0);
  if (!f.read(reinterpret_cast<char *>(out.data()), out.size())) {
    return false;
  }
  return true;
}
#endif

/** PNG eXIf chunk type (for meta_raw tag). */
static constexpr uint32_t kPngChunk_eXIf = 0x65584966u;

/** FNV-1a 64-bit offset basis and prime (for canonical pixel hash). */
static constexpr uint64_t kFnv1aOffsetBasis = 0xcbf29ce484222325ULL;
static constexpr uint64_t kFnv1aPrime = 0x100000001b3ULL;

/**
 * Compute canonical pixel hash of decoded raster: FNV-1a 64-bit over raw
 * pixel bytes, row-major top-down. Only the pixel data (width * bpp per row)
 * is hashed, not stride padding. Ensures decode is deterministic and
 * regression-free.
 */
uint64_t raster_pixel_hash(const GIMG_Raster * raster) {
  if (!raster) {
    return 0;
  }
  const GIMG_Pixel_Format * fmt = gimg_raster_format(raster);
  size_t bpp = gimg_raster_bytes_per_pixel(fmt);
  if (bpp == 0) {
    return 0;
  }
  uint32_t w = gimg_raster_width(raster);
  uint32_t h = gimg_raster_height(raster);
  size_t row_bytes = w * bpp;
  const unsigned char * pixels =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(
          const_cast<GIMG_Raster *>(raster)));
  size_t stride = gimg_raster_stride_bytes(raster);
  if (!pixels || stride < row_bytes) {
    return 0;
  }
  uint64_t hval = kFnv1aOffsetBasis;
  for (uint32_t y = 0; y < h; y++) {
    const unsigned char * row = pixels + y * stride;
    for (size_t i = 0; i < row_bytes; i++) {
      hval ^= static_cast<uint64_t>(row[i]);
      hval *= kFnv1aPrime;
    }
  }
  return hval;
}

} // namespace

TEST(PngDecode, DecodeNoIdatReturnsFormat) {
  // Minimal PNG (signature + IHDR + IEND, no IDAT). Decode should fail.
  std::vector<uint8_t> buf;
  append(buf, kPngSignature, sizeof(kPngSignature));
  append(buf, kIhdr1x1, sizeof(kIhdr1x1));
  append(buf, kIendChunk, sizeof(kIendChunk));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Item * item = gimg_doc_item(doc, 0);
  ASSERT_NE(item, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(item, nullptr, &raster);
  EXPECT_EQ(r, GIMG_ERR_FORMAT) << "decode with no IDAT should return FORMAT";
  EXPECT_EQ(raster, nullptr);

  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeEmptyIdatReturnsCorrupt) {
  // Minimal PNG with IDAT that decompresses to 0 bytes (empty stored block).
  const unsigned char kIdatEmpty[] = {0x00, 0x00, 0x00, 0x05, 0x49, 0x44, 0x41,
      0x54, 0x01, 0x00, 0x00, 0xFF, 0xFF, 0xCF, 0xCA, 0x62, 0x86};
  std::vector<uint8_t> buf;
  append(buf, kPngSignature, sizeof(kPngSignature));
  append(buf, kIhdr1x1, sizeof(kIhdr1x1));
  append(buf, kIdatEmpty, sizeof(kIdatEmpty));
  append(buf, kIendChunk, sizeof(kIendChunk));

  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  GIMG_Result r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Item * item = gimg_doc_item(doc, 0);
  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(item, nullptr, &raster);
  EXPECT_EQ(r, GIMG_ERR_CORRUPT) << "empty IDAT decompress should be corrupt";
  EXPECT_EQ(raster, nullptr);

  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

#ifdef GIMG_TEST_DATA_PNG

TEST(PngDecode, Decode1x1GrayFromFile) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_1x1_gray.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_GRAY);
  EXPECT_EQ(gimg_raster_bytes_per_pixel(gimg_raster_format(raster)), 1u);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0) << "1x1 gray black pixel";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, Decode1x1PaletteWithTrnsFromFile) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_1x1_palette.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_RGBA);
  EXPECT_EQ(gimg_raster_bytes_per_pixel(gimg_raster_format(raster)), 4u);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0x11);
  EXPECT_EQ(px[1], 0x22);
  EXPECT_EQ(px[2], 0x33);
  EXPECT_EQ(px[3], 0x80) << "tRNS alpha for palette index 0";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, Decode16bitGrayFromFile) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_16bit_gray.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_GRAY);
  EXPECT_EQ(gimg_raster_format(raster)->bits_per_channel[0], 16);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0x34) << "16-bit gray low byte 0x1234";
  EXPECT_EQ(px[1], 0x12) << "16-bit gray high byte";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, Decode1x1RgbaFromFile) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_1x1_rgba.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_RGBA);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0x11);
  EXPECT_EQ(px[1], 0x22);
  EXPECT_EQ(px[2], 0x33);
  EXPECT_EQ(px[3], 0x80);

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeSrgbSetsColorInfo) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_srgb.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  const GIMG_Color_Info * info = gimg_raster_color_info_const(raster);
  ASSERT_NE(info, nullptr);
  EXPECT_EQ(info->primaries, GIMG_PRIMARIES_SRGB);
  EXPECT_EQ(info->transfer, GIMG_TRANSFER_SRGB);
  EXPECT_EQ(info->intent, GIMG_INTENT_PERCEPTUAL) << "sRGB chunk intent 0 = Perceptual";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeExifAttachedToMetaRaw) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_exif.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Meta_Raw * raw = gimg_doc_meta_raw(doc);
  ASSERT_NE(raw, nullptr) << "eXIf chunk should attach doc meta_raw";

  size_t size = 0;
  r = gimg_meta_raw_get(raw, "png", kPngChunk_eXIf, nullptr, &size);
  ASSERT_EQ(r, GIMG_OK);
  EXPECT_EQ(size, 6u) << "eXIf payload in generate.py is 6 bytes";

  std::vector<uint8_t> exif_buf(size);
  r = gimg_meta_raw_get(raw, "png", kPngChunk_eXIf, exif_buf.data(), &size);
  ASSERT_EQ(r, GIMG_OK);
  EXPECT_EQ(size, 6u);
  EXPECT_EQ(exif_buf[0], 0x00);
  EXPECT_EQ(exif_buf[5], 0x05);

  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeIccpSetsColorInfo) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_iccp.png", buf)) << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  const GIMG_Color_Info * info = gimg_raster_color_info_const(raster);
  ASSERT_NE(info, nullptr);
  EXPECT_GT(info->icc_size, 0u) << "iCCP decompressed profile attached to raster";
  EXPECT_NE(info->icc_bytes, nullptr);

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ApngTwoFramesLoadAndDecode) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_apng_2frame.png", buf))
      << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  EXPECT_EQ(gimg_doc_item_count(doc), 2u) << "APNG has 2 frames";

  GIMG_Item * item0 = gimg_doc_item(doc, 0);
  GIMG_Item * item1 = gimg_doc_item(doc, 1);
  ASSERT_NE(item0, nullptr);
  ASSERT_NE(item1, nullptr);

  uint16_t num = 0;
  uint16_t den = 0;
  gimg_item_frame_delay(item0, &num, &den);
  EXPECT_EQ(num, 50u) << "frame 0 delay_num";
  EXPECT_EQ(den, 100u) << "frame 0 delay_den";
  EXPECT_EQ(gimg_item_dispose_op(item0), GIMG_DISPOSE_NONE);
  EXPECT_EQ(gimg_item_blend_op(item0), GIMG_BLEND_SOURCE);

  gimg_item_frame_delay(item1, &num, &den);
  EXPECT_EQ(num, 25u) << "frame 1 delay_num";
  EXPECT_EQ(den, 100u) << "frame 1 delay_den";
  EXPECT_EQ(gimg_item_dispose_op(item1), GIMG_DISPOSE_BACKGROUND);
  EXPECT_EQ(gimg_item_blend_op(item1), GIMG_BLEND_OVER);

  GIMG_Raster * raster0 = nullptr;
  r = gimg_item_decode(item0, nullptr, &raster0);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster0, nullptr);
  EXPECT_EQ(gimg_raster_width(raster0), 1u);
  EXPECT_EQ(gimg_raster_height(raster0), 1u);
  const unsigned char * px0 =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster0));
  ASSERT_NE(px0, nullptr);
  EXPECT_EQ(px0[0], 0) << "frame 0 is black (gray 0)";

  GIMG_Raster * raster1 = nullptr;
  r = gimg_item_decode(item1, nullptr, &raster1);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster1, nullptr);
  EXPECT_EQ(gimg_raster_width(raster1), 1u);
  EXPECT_EQ(gimg_raster_height(raster1), 1u);
  const unsigned char * px1 =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster1));
  ASSERT_NE(px1, nullptr);
  EXPECT_EQ(px1[0], 0x80) << "frame 1 is gray 0x80";

  gimg_raster_destroy(raster0);
  gimg_raster_destroy(raster1);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ApngThreeFramesLoadAndDecode) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_apng_3frame.png", buf))
      << "Run tests/data/png/generate.py";

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);
  gimg_stream_destroy(s);
  s = nullptr;

  EXPECT_EQ(gimg_doc_item_count(doc), 3u);

  uint16_t num = 0, den = 0;
  GIMG_Item * item0 = gimg_doc_item((GIMG_Doc *)doc, 0);
  GIMG_Item * item1 = gimg_doc_item((GIMG_Doc *)doc, 1);
  GIMG_Item * item2 = gimg_doc_item((GIMG_Doc *)doc, 2);
  ASSERT_NE(item0, nullptr);
  ASSERT_NE(item1, nullptr);
  ASSERT_NE(item2, nullptr);

  gimg_item_frame_delay(item0, &num, &den);
  EXPECT_EQ(num, 50u);
  EXPECT_EQ(den, 100u);
  EXPECT_EQ(gimg_item_dispose_op(item0), GIMG_DISPOSE_NONE);
  EXPECT_EQ(gimg_item_blend_op(item0), GIMG_BLEND_SOURCE);

  gimg_item_frame_delay(item1, &num, &den);
  EXPECT_EQ(num, 25u);
  EXPECT_EQ(den, 100u);
  EXPECT_EQ(gimg_item_dispose_op(item1), GIMG_DISPOSE_BACKGROUND);
  EXPECT_EQ(gimg_item_blend_op(item1), GIMG_BLEND_OVER);

  gimg_item_frame_delay(item2, &num, &den);
  EXPECT_EQ(num, 10u);
  EXPECT_EQ(den, 100u);
  EXPECT_EQ(gimg_item_dispose_op(item2), GIMG_DISPOSE_PREVIOUS);
  EXPECT_EQ(gimg_item_blend_op(item2), GIMG_BLEND_OVER);

  GIMG_Raster * r0 = nullptr;
  GIMG_Raster * r1 = nullptr;
  GIMG_Raster * r2 = nullptr;
  r = gimg_item_decode(item0, nullptr, &r0);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(r0, nullptr);
  r = gimg_item_decode(item1, nullptr, &r1);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(r1, nullptr);
  r = gimg_item_decode(item2, nullptr, &r2);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(r2, nullptr);

  EXPECT_EQ(static_cast<const unsigned char *>(gimg_raster_pixels_const(r0))[0],
            0);
  EXPECT_EQ(static_cast<const unsigned char *>(gimg_raster_pixels_const(r1))[0],
            0x80);
  EXPECT_EQ(static_cast<const unsigned char *>(gimg_raster_pixels_const(r2))[0],
            0xC0);

  gimg_raster_destroy(r0);
  gimg_raster_destroy(r1);
  gimg_raster_destroy(r2);
  gimg_doc_destroy(doc);
}

TEST(PngDecode, ApngTruncatedReturnsErrorNoCrash) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_apng_2frame.png", buf));

  // Truncate before IEND (e.g. remove last 20 bytes). Load should fail.
  if (buf.size() > 20) {
    buf.resize(buf.size() - 20);
  }
  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  EXPECT_NE(r, GIMG_OK);
  EXPECT_EQ(doc, nullptr);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ApngInvalidSignatureRejected) {
  // Not a PNG signature: load should fail with FORMAT or similar.
  std::vector<uint8_t> buf = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  EXPECT_NE(r, GIMG_OK);
  EXPECT_EQ(doc, nullptr);
  gimg_stream_destroy(s);
}

TEST(PngDecode, ApngMaxFrameCountLimitEnforced) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_apng_2frame.png", buf));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Limits limits = {};
  limits.max_frame_count = 1;
  GIMG_Load_Options opts = {&limits, GIMG_NORMAL, {0}};

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, &opts, nullptr, &doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(r, GIMG_ERR_LIMIT) << "acTL num_frames=2 exceeds max_frame_count=1";
  EXPECT_EQ(doc, nullptr);
}

TEST(PngDecode, ApngMaxChunkSizeLimitEnforced) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_1x1_gray.png", buf));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Limits limits = {};
  limits.max_chunk_size = 8;  // IHDR payload is 13 bytes
  GIMG_Load_Options opts = {&limits, GIMG_NORMAL, {0}};

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, &opts, nullptr, &doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(r, GIMG_ERR_LIMIT) << "IHDR length 13 exceeds max_chunk_size=8";
  EXPECT_EQ(doc, nullptr);
}

// ---- Golden-file decode tests: canonical pixel hash per reference file ----

TEST(PngDecode, Golden1x1Gray) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_1x1_gray.png", buf));
  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  uint64_t hash = raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 12638153115695167455ULL) << "canonical pixel hash 1x1 gray";
}

TEST(PngDecode, Golden1x1Palette) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_1x1_palette.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 15243095932836669713ULL) << "canonical pixel hash 1x1 palette+tRNS";
}

TEST(PngDecode, Golden16bitGray) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_16bit_gray.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 571567958656141443ULL) << "canonical pixel hash 16-bit gray";
}

TEST(PngDecode, Golden1x1Rgba) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_1x1_rgba.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 15243095932836669713ULL) << "canonical pixel hash 1x1 RGBA";
}

TEST(PngDecode, Golden16bitRgba) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_16bit_rgba.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 1173251487157325173ULL) << "canonical pixel hash 16-bit RGBA";
}

TEST(PngDecode, GoldenSrgb) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_srgb.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 12638153115695167455ULL) << "canonical pixel hash sRGB (same pixels as 1x1 gray)";
}

TEST(PngDecode, GoldenExif) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_exif.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 12638153115695167455ULL) << "canonical pixel hash eXIf (same pixels as 1x1 gray)";
}

TEST(PngDecode, GoldenIccp) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_iccp.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  GIMG_Raster * raster = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  uint64_t hash = raster_pixel_hash(raster);
  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash, 12638153115695167455ULL) << "canonical pixel hash iCCP (same pixels as 1x1 gray)";
}

TEST(PngDecode, GoldenApng2Frame) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_apng_2frame.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(gimg_doc_item_count(doc), 2u);
  uint64_t hash0 = 0, hash1 = 0;
  GIMG_Raster * r0 = nullptr;
  GIMG_Raster * r1 = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &r0);
  gimg_item_decode(gimg_doc_item(doc, 1), nullptr, &r1);
  hash0 = raster_pixel_hash(r0);
  hash1 = raster_pixel_hash(r1);
  gimg_raster_destroy(r0);
  gimg_raster_destroy(r1);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(hash0, 12638153115695167455ULL) << "APNG frame 0 pixel hash";
  EXPECT_EQ(hash1, 12638293853183578463ULL) << "APNG frame 1 pixel hash";
}

TEST(PngDecode, GoldenApng3Frame) {
  std::vector<uint8_t> buf;
  ASSERT_TRUE(load_png_file("png_apng_3frame.png", buf));
  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(gimg_doc_item_count(doc), 3u);
  GIMG_Raster * r0 = nullptr;
  GIMG_Raster * r1 = nullptr;
  GIMG_Raster * r2 = nullptr;
  gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &r0);
  gimg_item_decode(gimg_doc_item(doc, 1), nullptr, &r1);
  gimg_item_decode(gimg_doc_item(doc, 2), nullptr, &r2);
  uint64_t h0 = raster_pixel_hash(r0);
  uint64_t h1 = raster_pixel_hash(r1);
  uint64_t h2 = raster_pixel_hash(r2);
  gimg_raster_destroy(r0);
  gimg_raster_destroy(r1);
  gimg_raster_destroy(r2);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
  EXPECT_EQ(h0, 12638153115695167455ULL) << "APNG 3-frame: frame 0";
  EXPECT_EQ(h1, 12638293853183578463ULL) << "APNG 3-frame: frame 1";
  EXPECT_EQ(h2, 12638364221927783967ULL) << "APNG 3-frame: frame 2";
}

#endif // GIMG_TEST_DATA_PNG

int main(int argc, char ** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
