/**
 * @file
 *
 * PNG decode tests: DEFLATE, filters, raster output.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#include <cstdint>
#include <cstring>
#include <ghoti.io/image/codec.h>
#include <ghoti.io/image/doc.h>
#include <ghoti.io/image/raster.h>
#include <ghoti.io/image/stream.h>
#include <gtest/gtest.h>
#include <vector>

namespace {

const unsigned char kPngSignature[] = {
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A};

// IHDR: 1x1 grayscale 8-bit.
const unsigned char kIhdr1x1[] = {0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44,
    0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x00, 0x00,
    0x00, 0x00, 0x3A, 0x7E, 0x9B, 0x55};

// IDAT for 1x1 image: zlib (78 01) + raw deflate stored block (2 bytes 0x00 0x00)
// + Adler-32. Generated by tests/codec/png/gen_1x1_png.py (source of truth).
const unsigned char kIdat1x1[] = {0x00, 0x00, 0x00, 0x0D, 0x49, 0x44, 0x41,
    0x54, 0x78, 0x01, 0x01, 0x02, 0x00, 0xFD, 0xFF, 0x00, 0x00, 0x00, 0x02,
    0x00, 0x01, 0x7E, 0x05, 0x0D, 0xD2};

const unsigned char kIendChunk[] = {
    0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82};

// Minimal 1x1 grayscale PNG (black pixel). From gen_1x1_png.py (source of truth).
const unsigned char kPng1x1Gray[] = {
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D,
    0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
    0x08, 0x00, 0x00, 0x00, 0x00, 0x3A, 0x7E, 0x9B, 0x55, 0x00, 0x00, 0x00,
    0x0D, 0x49, 0x44, 0x41, 0x54, 0x78, 0x01, 0x01, 0x02, 0x00, 0xFD, 0xFF,
    0x00, 0x00, 0x00, 0x02, 0x00, 0x01, 0x7E, 0x05, 0x0D, 0xD2, 0x00, 0x00,
    0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82};

// IHDR 1x1 palette 8-bit. CRCs from gen_1x1_png.py (source of truth).
const unsigned char kIhdr1x1Palette[] = {0x00, 0x00, 0x00, 0x0D, 0x49, 0x48,
    0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x03,
    0x00, 0x00, 0x00, 0x28, 0xCB, 0x34, 0xBB};
// PLTE 1 entry (R=0x11 G=0x22 B=0x33). CRCs from gen_1x1_png.py.
const unsigned char kPlte1Entry[] = {0x00, 0x00, 0x00, 0x03, 0x50, 0x4C, 0x54,
    0x45, 0x11, 0x22, 0x33, 0xA2, 0xFC, 0xD3, 0xAB};
// tRNS 1 byte (alpha 0x80 for palette index 0).
const unsigned char kTrns1Entry[] = {0x00, 0x00, 0x00, 0x01, 0x74, 0x52, 0x4E,
    0x53, 0x80, 0xAD, 0x5E, 0x5B, 0x46};

void append(std::vector<uint8_t> & out, const unsigned char * p, size_t n) {
  out.insert(out.end(), p, p + n);
}

} // namespace

TEST(PngDecode, DecodeNoIdatReturnsFormat) {
  // Minimal PNG (signature + IHDR + IEND, no IDAT). Decode should fail.
  std::vector<uint8_t> buf;
  append(buf, kPngSignature, sizeof(kPngSignature));
  append(buf, kIhdr1x1, sizeof(kIhdr1x1));
  append(buf, kIendChunk, sizeof(kIendChunk));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Item * item = gimg_doc_item(doc, 0);
  ASSERT_NE(item, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(item, nullptr, &raster);
  EXPECT_EQ(r, GIMG_ERR_FORMAT) << "decode with no IDAT should return FORMAT";
  EXPECT_EQ(raster, nullptr);

  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, DecodeEmptyIdatReturnsCorrupt) {
  // Minimal PNG with IDAT that decompresses to 0 bytes (empty stored block).
  // Expected raw size for 1x1 gray is 2; decompress yields 0 -> corrupt.
  const unsigned char kIdatEmpty[] = {0x00, 0x00, 0x00, 0x05, 0x49, 0x44, 0x41,
      0x54, 0x01, 0x00, 0x00, 0xFF, 0xFF, 0xCF, 0xCA, 0x62, 0x86};
  std::vector<uint8_t> buf;
  append(buf, kPngSignature, sizeof(kPngSignature));
  append(buf, kIhdr1x1, sizeof(kIhdr1x1));
  append(buf, kIdatEmpty, sizeof(kIdatEmpty));
  append(buf, kIendChunk, sizeof(kIendChunk));

  GIMG_Stream * s = nullptr;
  gimg_stream_create_memory(buf.data(), buf.size(), &s);
  GIMG_Doc * doc = nullptr;
  GIMG_Result r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Item * item = gimg_doc_item(doc, 0);
  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(item, nullptr, &raster);
  EXPECT_EQ(r, GIMG_ERR_CORRUPT) << "empty IDAT decompress should be corrupt";
  EXPECT_EQ(raster, nullptr);

  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

TEST(PngDecode, Decode1x1GraySucceeds) {
  std::vector<uint8_t> buf(kPng1x1Gray,
      kPng1x1Gray + sizeof(kPng1x1Gray));
  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_GRAY);
  EXPECT_EQ(gimg_raster_bytes_per_pixel(gimg_raster_format(raster)), 1u);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0) << "1x1 gray black pixel";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

// 1x1 palette + tRNS; chunk bytes (including CRCs) from gen_1x1_png.py.
TEST(PngDecode, Decode1x1PaletteWithTrnsSucceeds) {
  std::vector<uint8_t> buf;
  append(buf, kPngSignature, sizeof(kPngSignature));
  append(buf, kIhdr1x1Palette, sizeof(kIhdr1x1Palette));
  append(buf, kPlte1Entry, sizeof(kPlte1Entry));
  append(buf, kTrns1Entry, sizeof(kTrns1Entry));
  append(buf, kIdat1x1, sizeof(kIdat1x1));
  append(buf, kIendChunk, sizeof(kIendChunk));

  GIMG_Stream * s = nullptr;
  GIMG_Result r = gimg_stream_create_memory(buf.data(), buf.size(), &s);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(s, nullptr);

  GIMG_Doc * doc = nullptr;
  r = gimg_doc_load(s, nullptr, nullptr, &doc);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(doc, nullptr);

  GIMG_Raster * raster = nullptr;
  r = gimg_item_decode(gimg_doc_item(doc, 0), nullptr, &raster);
  ASSERT_EQ(r, GIMG_OK);
  ASSERT_NE(raster, nullptr);

  EXPECT_EQ(gimg_raster_width(raster), 1u);
  EXPECT_EQ(gimg_raster_height(raster), 1u);
  EXPECT_EQ(gimg_raster_format(raster)->channel_model, GIMG_CHANNEL_RGBA);
  EXPECT_EQ(gimg_raster_bytes_per_pixel(gimg_raster_format(raster)), 4u);
  const unsigned char * px =
      static_cast<const unsigned char *>(gimg_raster_pixels_const(raster));
  ASSERT_NE(px, nullptr);
  EXPECT_EQ(px[0], 0x11);
  EXPECT_EQ(px[1], 0x22);
  EXPECT_EQ(px[2], 0x33);
  EXPECT_EQ(px[3], 0x80) << "tRNS alpha for palette index 0";

  gimg_raster_destroy(raster);
  gimg_doc_destroy(doc);
  gimg_stream_destroy(s);
}

int main(int argc, char ** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
